import {z} from 'zod';
import {notifyLead} from '@/lib/email-notifications';
import {getRawDb} from '@/db/raw';
import {student,sameOrigin,readJSON,limited,hashPassword,newSession,logout} from '@/lib/platform-security';
import {rows} from '@/lib/platform-store';
import {getUniversity,listUniversities} from '@/lib/university-store';
import {getCountry} from '@/lib/country-store';
import {contentRows} from '@/lib/platform-store';
import {journeyDraftSchema,guestSaveSchema,preferencesSchema,profileCompletion,type GuestSave} from '@/lib/journey-draft';
import {initialJourney,reviewSchema,storySchema} from '@/lib/student-model';
export const dynamic='force-dynamic';
export async function GET(r:Request){try{const a=await student(r);if(!a)return Response.json({student:null},{headers:{'Cache-Control':'no-store'}});const journeys=await rows("SELECT json_object('id',id,'universityId',university_id,'programId',program_id,'content',json(content),'updatedAt',updated_at) AS item FROM student_journeys WHERE student_id=? ORDER BY updated_at DESC LIMIT 50",[a.id]);const saved=await rows("SELECT json_object('kind',kind,'itemId',item_id,'content',json(content)) AS item FROM saved_items WHERE student_id=? ORDER BY created_at DESC LIMIT 200",[a.id]);const reviews=await rows("SELECT json_object('id',id,'universityId',university_id,'status',status) AS item FROM student_reviews WHERE student_id=? LIMIT 50",[a.id]);const trips=await rows("SELECT json_object('id',id,'kind',kind,'status',status,'universityId',university_id,'content',json(content)) AS item FROM travel_requests WHERE student_id=? ORDER BY created_at DESC LIMIT 100",[a.id]);const questions=await rows("SELECT json_object('id',id,'question',question,'answer',answer,'status',status) AS item FROM ambassador_questions WHERE student_id=? OR (ambassador_id=? AND status IN ('approved','answered')) ORDER BY created_at DESC LIMIT 50",[a.id,a.id]);const personal=await getRawDb().prepare('SELECT preferences,profile FROM student_preferences WHERE student_id=?').bind(a.id).first<{preferences:string,profile:string}>();const preferences=preferencesSchema.parse(JSON.parse(personal?.preferences||'{}')),profile=JSON.parse(personal?.profile||'{}');return Response.json({student:a,journeys,saved,reviews,trips,questions,preferences,profile,profileCompletion:profileCompletion(profile,preferences)},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Account unavailable'},{status:503});}}
async function ownedMedia(studentId:string,ids:string[],evidence=false){for(const id of ids){const row=await getRawDb().prepare("SELECT content FROM platform_content WHERE id=? AND kind='media'").bind(id.replace('/api/university-media/','')).first<{content:string}>();if(!row)return false;const d=JSON.parse(row.content);if(d.owner!==studentId||!!d.evidence!==evidence)return false;}return true;}

async function canonicalSave(item:GuestSave):Promise<GuestSave|null>{
 if(item.kind==='country'){const country=await getCountry(item.itemId);return country?{kind:'country',itemId:country.slug,content:{countryCode:country.code as GuestSave['content']['countryCode']}}:null;}
 if(item.kind==='university'){const u=await getUniversity(item.itemId);return u?{kind:item.kind,itemId:u.slug,content:{title:u.name.en}}:null;}
 if(item.kind==='program'){const [slug,...ids]=item.itemId.split('/'),u=await getUniversity(slug),id=ids.join('/'),program=u?.programs.find(p=>p.id===id);return program&&u?{kind:item.kind,itemId:`${u.slug}/${program.id}`,content:{title:program.name,universitySlug:u.slug,programId:program.id}}:null;}
 if(item.kind==='comparison'){const slugs=item.content.universities;if(!slugs?.length)return null;const universities=await listUniversities();if(slugs.some(slug=>!universities.some(u=>u.slug===slug)))return null;const unique=[...new Set(slugs)].sort();return {kind:item.kind,itemId:unique.join(','),content:{universities:unique}};}
 const records=await contentRows(item.kind),record=records.find(r=>r.id===item.itemId);return record?{kind:item.kind,itemId:record.id,content:{}}:null;
}
export async function POST(r:Request){if(!sameOrigin(r))return Response.json({error:'Invalid origin'},{status:403});try{if(await limited(r,'student-write',50))return Response.json({error:'Please retry later'},{status:429});const p=await readJSON(r,50000),db=getRawDb();if(['signup','login'].includes(p.action)){if(await limited(r,'student-login',10))return Response.json({error:'Please retry later'},{status:429});const auth=z.object({email:z.string().email().max(254).transform(v=>v.trim().toLowerCase()),password:z.string().min(12).max(200),name:z.string().trim().min(2).max(100).optional(),firstName:z.string().trim().min(1).max(60).optional(),lastName:z.string().trim().min(1).max(60).optional(),phone:z.string().trim().max(30).regex(/^$|^\+?[\d\s()\-]{5,30}$/).optional()}).parse(p);const existing=await db.prepare('SELECT id,password_hash FROM student_accounts WHERE email=?').bind(auth.email).first<{id:string,password_hash:string}>();let id:string;if(p.action==='signup'){if(existing)return Response.json({error:'This email is registered; sign in'},{status:409});const name=auth.name||[auth.firstName,auth.lastName].filter(Boolean).join(' ');if(name.length<2)return Response.json({error:'Name required'},{status:400});id=crypto.randomUUID();await db.batch([db.prepare('INSERT INTO student_accounts(id,email,name,password_hash,created_at) VALUES(?,?,?,?,?)').bind(id,auth.email,name,await hashPassword(auth.password),Date.now()),db.prepare('INSERT INTO student_preferences(student_id,preferences,profile,updated_at) VALUES(?,?,?,?)').bind(id,'{}',JSON.stringify({firstName:auth.firstName||auth.name?.split(' ')[0]||'',lastName:auth.lastName||'',phone:auth.phone||''}),Date.now())]);}else{if(!existing){await hashPassword(auth.password);return Response.json({error:'Invalid email or password'},{status:401});}if(await hashPassword(auth.password,existing.password_hash.split(':')[0])!==existing.password_hash)return Response.json({error:'Invalid email or password'},{status:401});id=existing.id;}return Response.json({ok:true},{headers:{'Set-Cookie':await newSession(id)}});}
if(p.action==='logout')return Response.json({ok:true},{headers:{'Set-Cookie':await logout(r)}});const a=await student(r);if(!a)return Response.json({error:'Please sign in'},{status:401});
if(p.action==='sync-draft'){const draft=journeyDraftSchema.parse(p.draft);if(draft.preferences.countryCode&&!await getCountry(draft.preferences.countryCode))return Response.json({error:'Unknown country'},{status:400});const validated:GuestSave[]=[];for(const item of draft.saved){const value=await canonicalSave(item);if(!value)return Response.json({error:'A saved option is no longer available; please review your choices'},{status:400});validated.push(value);}const unique=new Map(validated.map(s=>[`${s.kind}:${s.itemId}`,s]));const statements=[db.prepare('INSERT INTO student_preferences(student_id,preferences,profile,updated_at) VALUES(?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET preferences=json_patch(preferences,excluded.preferences),updated_at=excluded.updated_at').bind(a.id,JSON.stringify(draft.preferences),'{}',Date.now()),...[...unique.values()].map(s=>db.prepare('INSERT INTO saved_items(student_id,kind,item_id,content,created_at) VALUES(?,?,?,?,?) ON CONFLICT(student_id,kind,item_id) DO UPDATE SET content=excluded.content').bind(a.id,s.kind,s.itemId,JSON.stringify(s.content),Date.now()))];await db.batch(statements);return Response.json({ok:true,imported:unique.size});}
if(p.action==='preferences'){const preferences=preferencesSchema.parse(p.preferences);if(preferences.countryCode&&!await getCountry(preferences.countryCode))return Response.json({error:'Unknown country'},{status:400});await db.prepare('INSERT INTO student_preferences(student_id,preferences,profile,updated_at) VALUES(?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET preferences=excluded.preferences,updated_at=excluded.updated_at').bind(a.id,JSON.stringify(preferences),'{}',Date.now()).run();return Response.json({ok:true});}
if(p.action==='profile'){const profile=z.object({firstName:z.string().trim().min(1).max(60),lastName:z.string().trim().max(60),phone:z.string().trim().max(30).regex(/^$|^\+?[\d\s()\-]{5,30}$/),homeCountry:z.string().trim().max(80),education:z.enum(['','high-school','bachelor','master','phd','other'])}).parse(p.profile);await db.prepare('INSERT INTO student_preferences(student_id,preferences,profile,updated_at) VALUES(?,?,?,?) ON CONFLICT(student_id) DO UPDATE SET profile=excluded.profile,updated_at=excluded.updated_at').bind(a.id,'{}',JSON.stringify(profile),Date.now()).run();return Response.json({ok:true});}
if(p.action==='save'){const item=guestSaveSchema.parse(p),s=await canonicalSave(item);if(!s)return Response.json({error:'Unknown saved option'},{status:400});await db.prepare('INSERT INTO saved_items(student_id,kind,item_id,content,created_at) VALUES(?,?,?,?,?) ON CONFLICT(student_id,kind,item_id) DO UPDATE SET content=excluded.content').bind(a.id,s.kind,s.itemId,JSON.stringify(s.content),Date.now()).run();return Response.json({ok:true});}
if(p.action==='unsave'){const s=z.object({kind:z.string().max(50),itemId:z.string().max(300)}).parse(p);await db.prepare('DELETE FROM saved_items WHERE student_id=? AND kind=? AND item_id=?').bind(a.id,s.kind,s.itemId).run();return Response.json({ok:true});}
if(p.action==='report'){const s=z.object({kind:z.enum(['review','story','question']),itemId:z.string().max(120),reason:z.string().min(10).max(1500)}).parse(p);await db.prepare('INSERT INTO platform_reports(id,student_id,kind,item_id,reason,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),a.id,s.kind,s.itemId,s.reason,Date.now()).run();return Response.json({ok:true});}
const slug=z.string().min(2).max(100).parse(p.university),u=await getUniversity(slug);if(!u)return Response.json({error:'Unknown university'},{status:404});
if(p.action==='apply'){z.literal(true).parse(p.consent);const program=z.string().min(1).max(120).parse(p.programId);if(!u.programs.some(x=>x.id===program)&&program!=='individual-review')return Response.json({error:'Unknown program'},{status:400});const current=await db.prepare('SELECT id FROM student_journeys WHERE student_id=? AND university_id=? AND program_id=?').bind(a.id,u.id,program).first<{id:string}>();if(current)return Response.json({ok:true,id:current.id});const data=initialJourney();data.stages[2].status='waiting_university';const id=crypto.randomUUID();await db.prepare('INSERT INTO student_journeys(id,student_id,university_id,program_id,content,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,a.id,u.id,program,JSON.stringify(data),Date.now(),Date.now()).run();await notifyLead(id,{code:'CG-'+id.replace(/-/g,'').slice(0,16).toUpperCase(),name:a.name,email:a.email,phone:'',service:'study-abroad',destination:u.name.en,message:'Student account admission review request: '+(u.programs.find(x=>x.id===program)?.name||'Individual review'),method:'email'});return Response.json({ok:true,id});}
if(p.action==='review'){const value=reviewSchema.parse(p.content);if(value.yearStarted>new Date().getFullYear())return Response.json({error:'Year cannot be in the future'},{status:400});if(!await ownedMedia(a.id,value.photos)||!await ownedMedia(a.id,value.evidence,true))return Response.json({error:'Invalid media ownership'},{status:403});const exists=await db.prepare('SELECT id FROM student_reviews WHERE student_id=? AND university_id=?').bind(a.id,u.id).first();if(exists)return Response.json({error:'One review per university; contact support to edit'},{status:409});const id=crypto.randomUUID();await db.prepare('INSERT INTO student_reviews(id,student_id,university_id,content,evidence,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').bind(id,a.id,u.id,JSON.stringify(value),JSON.stringify(value.evidence),Date.now(),Date.now()).run();return Response.json({ok:true,id,status:'verification_pending'});}
if(p.action==='story'){if(await limited(r,'story-submit',5,86400000))return Response.json({error:'Please retry later'},{status:429});const value=storySchema.parse(p.content);if(!await ownedMedia(a.id,value.photos))return Response.json({error:'Invalid media ownership'},{status:403});const id=crypto.randomUUID();await db.prepare('INSERT INTO student_stories(id,student_id,university_id,content,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(id,a.id,u.id,JSON.stringify(value),Date.now(),Date.now()).run();return Response.json({ok:true,id});}
if(p.action==='ambassador'){const opted=z.boolean().parse(p.optedIn);const verified=await db.prepare("SELECT id FROM student_reviews WHERE student_id=? AND university_id=? AND status IN ('verified_student','verified_graduate')").bind(a.id,u.id).first();if(opted&&!verified)return Response.json({error:'Verified student status required'},{status:403});await db.prepare('INSERT INTO student_ambassadors(student_id,university_id,opted_in,created_at) VALUES(?,?,?,?) ON CONFLICT(student_id,university_id) DO UPDATE SET opted_in=excluded.opted_in').bind(a.id,u.id,opted?1:0,Date.now()).run();return Response.json({ok:true});}
if(p.action==='ask-student'){const q=z.string().min(10).max(2000).parse(p.question);const ambassador=await db.prepare("SELECT a.student_id FROM student_ambassadors a WHERE a.university_id=? AND a.opted_in=1 AND a.blocked=0 AND a.student_id<>? AND EXISTS(SELECT 1 FROM student_reviews r WHERE r.student_id=a.student_id AND r.university_id=a.university_id AND r.status IN ('verified_student','verified_graduate')) LIMIT 1").bind(u.id,a.id).first<{student_id:string}>();if(!ambassador)return Response.json({error:'No verified ambassador available; request consultation'},{status:409});await db.prepare('INSERT INTO ambassador_questions(id,student_id,university_id,ambassador_id,question,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),a.id,u.id,ambassador.student_id,q,Date.now()).run();return Response.json({ok:true});}
if(p.action==='answer-student'){const s=z.object({id:z.string().uuid(),answer:z.string().min(10).max(3000)}).parse(p);const ambassador=await db.prepare('SELECT opted_in,blocked FROM student_ambassadors WHERE student_id=? AND university_id=?').bind(a.id,u.id).first<{opted_in:number,blocked:number}>();if(!ambassador?.opted_in||ambassador.blocked)return Response.json({error:'Ambassador not active'},{status:403});const changed=await db.prepare("UPDATE ambassador_questions SET answer=?,status='answer_pending' WHERE id=? AND ambassador_id=? AND status='approved'").bind(s.answer,s.id,a.id).run();return Response.json({ok:changed.meta.changes>0});}
if(p.action==='travel'){const v=z.object({kind:z.enum(['hotel','flight','accommodation','transfer']),fields:z.record(z.string().max(100),z.string().max(1000)).refine(x=>Object.keys(x).length<=30),consent:z.literal(true)}).parse(p);if(v.kind==='hotel'&&(!v.fields.checkIn||!v.fields.checkOut||v.fields.checkOut<=v.fields.checkIn))return Response.json({error:'Check hotel dates'},{status:400});if(v.kind==='flight'&&!v.fields.departure)return Response.json({error:'Departure date required'},{status:400});const id=crypto.randomUUID();await db.prepare('INSERT INTO travel_requests(id,student_id,university_id,kind,content,created_at) VALUES(?,?,?,?,?,?)').bind(id,a.id,u.id,v.kind,JSON.stringify(v.fields),Date.now()).run();await notifyLead(id,{code:'CG-'+id.replace(/-/g,'').slice(0,16).toUpperCase(),name:a.name,email:a.email,phone:'',service:v.kind==='hotel'?'hotel-reservation':v.kind,destination:u.name.en,message:'Student account travel assistance request',details:v.fields,method:'email'});return Response.json({ok:true,id,status:'requested'});}
return Response.json({error:'Unknown action'},{status:400});}catch(e){if(e instanceof z.ZodError)return Response.json({error:'Please check all required fields'},{status:400});console.error('Student operation unavailable');return Response.json({error:'Please retry; request was not confirmed'},{status:503});}}
