import {getUniversity} from '@/lib/university-store';
import {reviewData} from '@/lib/platform-store';
import {student,sameOrigin,limited,readJSON} from '@/lib/platform-security';
import {getRawDb} from '@/db/raw';
import {T} from '@/app/international-data';
const feeBasis={annual:{fa:'سالانه',en:'Annual',tr:'Yıllık'},program:{fa:'کل برنامه',en:'Total programme',tr:'Tüm program'},source:{fa:'دورهٔ پرداخت نیازمند تأیید',en:'Billing period to confirm',tr:'Ödeme dönemi teyit edilmeli'}};
import {z} from 'zod';
const schema=z.object({question:z.string().min(1).max(500),language:z.enum(['fa','en','tr']),programId:z.string().max(120).optional()});
export async function POST(r:Request,{params}:{params:Promise<{slug:string}>}){if(!sameOrigin(r))return Response.json({error:'Invalid origin'},{status:403});try{if(await limited(r,'assistant',30))return Response.json({error:'Retry later'},{status:429});const p=schema.parse(await readJSON(r,5000)),u=await getUniversity((await params).slug);if(!u)return Response.json({error:'Not found'},{status:404});const l=p.language,q=p.question.toLocaleLowerCase('tr'),sources:{label:string,url:string}[]=[];let answer='';const fallback=T('این اطلاعات برای این دانشگاه هنوز تأیید و ثبت نشده است. برای ارزیابی با Creator Group تماس بگیرید.','This information has not been verified and recorded for this university. Contact Creator Group for evaluation.','Bu bilgi bu üniversite için henüz doğrulanıp kaydedilmedi. Değerlendirme için Creator Group ile iletişime geçin.')[l];
if(/next|مرحله|sonraki/.test(q)){const account=await student(r);if(account){const j=await getRawDb().prepare('SELECT content FROM student_journeys WHERE student_id=? AND university_id=? ORDER BY updated_at DESC LIMIT 1').bind(account.id,u.id).first<{content:string}>();if(j){const stages=JSON.parse(j.content).stages;const next=stages.find((s:{status:string})=>s.status!=='completed');answer=next?.action||fallback;}}}
else if(/review|student.*think|نظر|رضایت|öğrenci.*düşün/.test(q)){const data=await reviewData(u.id);answer=data.score.available?T(`امتیاز ${data.score.overall}/۱۰ از ${data.score.count} نظر دانشجوی تأییدشده. این‌ها تجربهٔ دانشجویان هستند، نه نظر رسمی دانشگاه.`,`Score ${data.score.overall}/10 from ${data.score.count} verified student reviews. These are student experiences, not official university facts.`,`${data.score.count} doğrulanmış öğrenci yorumundan ${data.score.overall}/10 puan. Bunlar öğrenci deneyimleridir, resmî üniversite bilgisi değildir.`)[l]:T('هنوز نظر تأییدشدهٔ کافی وجود ندارد.','Not enough verified student reviews yet.','Henüz yeterli doğrulanmış öğrenci yorumu yok.')[l];}
else if(/document|مدارک|belge|requirement/.test(q)){answer=u.admissionRequirements.map(x=>`${x.title[l]}: ${x.body[l]}`).join('\n\n');u.admissionRequirements.forEach(x=>{if(x.source)sources.push({label:x.title[l],url:x.source});});}
else if(/dorm|خوابگاه|yurt/.test(q))answer=u.dormitory[l];
else if(/living|زندگی|yaşam|stay|اقامت|konaklama/.test(q))answer=u.livingCosts[l];
else if(/apply|اپلای|درخواست|başvur/.test(q)){answer=T('برای ثبت درخواست، از فرم پذیرش همین صفحه یا حساب «مسیر دانشجویی من» استفاده کنید. ثبت درخواست به معنی پذیرش دانشگاه نیست.','Use this page’s application form or My Creator Journey account to submit your request. Submission is not university admission.','Talebinizi bu sayfadaki başvuru formuyla veya Creator yolculuğum hesabıyla gönderin. Talep üniversite kabulü anlamına gelmez.')[l];}
else{let programmes=u.programs.filter(x=>!x.sourceVersion||x.sourceVersion==='25-15');if(/dent|diş|دندان/.test(q))programmes=programmes.filter(x=>/dent|diş/i.test(x.name));else if(/medicine|tıp|پزشکی/.test(q))programmes=programmes.filter(x=>/medicine|tıp/i.test(x.name));else if(/english|انگلیسی|ingilizce/.test(q))programmes=programmes.filter(x=>x.language==='English');else{const terms=q.split(/\s+/).filter(x=>x.length>3);programmes=programmes.filter(x=>terms.some(t=>x.name.toLocaleLowerCase('tr').includes(t)));}if(p.programId&&/this program|این رشته|bu program/.test(q))programmes=u.programs.filter(x=>x.id===p.programId);if(programmes.length){answer=programmes.slice(0,6).map(x=>`${x.name}\n${x.originalTuition} — ${feeBasis[x.basis][l]}${x.discounts.length?'\n'+x.discounts.map(d=>`${d.label[l]}: ${d.value}`).join('; '):''}`).join('\n\n')+'\n\n'+u.feeNotice[l];for(const x of programmes.slice(0,6))if(!sources.some(s=>s.url===x.source))sources.push({label:x.sourceVersion||'2026–2027',url:x.source});}}
return Response.json({answer:answer||fallback,sources,mode:'verified-data',university:u.slug});}catch{return Response.json({error:'Assistant unavailable'},{status:503});}}
