'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeftRight,RefreshCw} from 'lucide-react';
import type {Language} from './content';
import {T} from './international-data';
const currencies=['USD','EUR','GBP','TRY','AED','CNY','RUB','CHF','CAD','AUD','JPY','SAR','IRR'];
type Rates={rates:Record<string,number>;updatedAt:number|null;nextUpdateAt:number|null;iran?:{rate:number;updatedAt:number;checkedAt:number;sourceUrl:string}|null};
export default function ExchangeOnline({lang}:{lang:Language}){
 const host=useRef<HTMLDivElement>(null);const [rates,setRates]=useState<Rates|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[amount,setAmount]=useState('1000'),[from,setFrom]=useState('USD'),[to,setTo]=useState('TRY');
 const locale=lang==='fa'?'fa-IR':lang==='tr'?'tr-TR':'en-GB';
 const refresh=useCallback(async(signal?:AbortSignal)=>{setBusy(true);try{const r=await fetch('/api/exchange-rates',{signal,cache:'no-store'});if(!r.ok)throw Error();const d=await r.json() as Rates;setRates(d);setError(false);}catch{if(!signal?.aborted)setError(true);}finally{if(!signal?.aborted)setBusy(false);}},[]);
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=setInterval(()=>void refresh(controller.signal),60000);const onVisible=()=>{if(document.visibilityState==='visible')void refresh(controller.signal);};document.addEventListener('visibilitychange',onVisible);return()=>{controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',onVisible);};},[refresh]);
 useEffect(()=>{const container=host.current;if(!container)return;const widget=document.createElement('tv-forex-table');widget.setAttribute('currencies',['USD','EUR','GBP','TRY','CHF','JPY','CAD','AUD'].join(','));widget.setAttribute('theme','light');widget.style.cssText='display:block;width:100%;height:500px;';container.appendChild(widget);if(!document.querySelector('script[data-creator-forex]')){const script=document.createElement('script');script.type='module';script.src='https://widgets.tradingview-widget.com/w/en/tv-forex-table.js';script.dataset.creatorForex='true';document.head.appendChild(script);}return()=>{widget.remove();};},[]);
 const n=Number(amount),valid=amount.trim()!==''&&Number.isFinite(n)&&n>=0&&n<=1e12;
 const iranPair=from==='IRR'||to==='IRR';
 const iranAvailable=!!rates?.iran&&Date.now()-rates.iran.checkedAt<120000&&Date.now()-rates.iran.updatedAt<=72*3600000&&!error;
 const rate=rates&&(!iranPair||iranAvailable)&&rates.rates[to]&&rates.rates[from]?rates.rates[to]/rates.rates[from]:null;
 const stale=!!rates&&!iranPair&&(error||(rates.updatedAt!==null&&Date.now()-rates.updatedAt>172800000));
 const format=(v:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:6}).format(v);
 return <section className="intl-exchange-online" aria-labelledby="online-exchange-title"><div className="intl-exchange-heading"><div><span className="intl-eyebrow">{T('بازار ارز آنلاین','Currency market online','Çevrim içi döviz piyasası')[lang]}</span><h2 id="online-exchange-title">{T('نرخ ارز و تبدیل آنلاین','Exchange rates & online conversion','Döviz kurları ve çevrim içi dönüşüm')[lang]}</h2></div><span className="intl-rate-tag">{T('دادهٔ آنلاین','Online data','Çevrim içi veri')[lang]}</span></div>
 <p>{T('جدول بازار با داده‌های TradingView به‌روزرسانی می‌شود. در تعطیلی بازار یا بسته به منبع، آخرین نرخ موجود نمایش داده می‌شود.','The market table updates with TradingView data. When markets are closed, or depending on the feed, it shows the latest available quote.','Piyasa tablosu TradingView verileriyle güncellenir. Piyasa kapalıyken veya veri kaynağına göre son mevcut fiyat gösterilir.')[lang]}</p>
 <div className="intl-forex-scroll" dir="ltr"><div ref={host} className="intl-forex-widget"/></div><p className="intl-rate-source"><a href="https://www.tradingview.com/markets/currencies/" target="_blank" rel="noopener noreferrer">{T('مشاهدهٔ بازار ارز در TradingView','View currency markets on TradingView','TradingView döviz piyasalarını aç')[lang]}</a></p>
 <div className="intl-currency-calculator"><div className="intl-exchange-heading"><h3>{T('محاسبهٔ تبدیل ارز','Currency converter','Döviz hesaplayıcı')[lang]}</h3><button type="button" className="intl-rate-refresh" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>{T('به‌روزرسانی','Refresh','Yenile')[lang]}</button></div><div className="intl-converter-inputs"><label>{T('مبلغ','Amount','Tutar')[lang]}<input type="number" dir="ltr" min="0" max="1000000000000" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{T('از ارز','From','Kaynak')[lang]}<select value={from} onChange={e=>setFrom(e.target.value)} dir="ltr">{currencies.map(c=><option key={c} value={c}>{c}</option>)}</select></label><button className="intl-currency-swap" type="button" aria-label={T('جابه‌جایی ارزها','Swap currencies','Para birimlerini değiştir')[lang]} onClick={()=>{setFrom(to);setTo(from);}}><ArrowLeftRight size={20}/></button><label>{T('به ارز','To','Hedef')[lang]}<select value={to} onChange={e=>setTo(e.target.value)} dir="ltr">{currencies.map(c=><option key={c} value={c}>{c}</option>)}</select></label></div>
 <div className="intl-converter-result" aria-live="polite">{!rates?<p>{busy?T('دریافت نرخ‌ها…','Loading rates…','Kurlar yükleniyor…')[lang]:T('نرخ‌ها موقتاً در دسترس نیستند؛ دوباره تلاش کنید.','Rates are temporarily unavailable. Please retry.','Kurlar geçici olarak kullanılamıyor. Yeniden deneyin.')[lang]}</p>:!valid?<p>{T('یک مبلغ معتبر وارد کنید.','Enter a valid amount.','Geçerli bir tutar girin.')[lang]}</p>:rate===null?<p>{T('نرخ معتبر برای این تبدیل موقتاً در دسترس نیست؛ محاسبه با نرخ جایگزین انجام نمی‌شود.','A valid rate for this conversion is temporarily unavailable; no substitute rate is used.','Bu dönüşüm için geçerli kur geçici olarak kullanılamıyor; yerine başka bir kur kullanılmaz.')[lang]}</p>:<><strong dir="ltr">{format(n*rate!)} {to}</strong><span dir="ltr">1 {from} = {format(rate!)} {to}</span></>}</div>
 {stale&&<p role="alert" className="intl-form-error">{T('نرخ جدید در دسترس نیست؛ نتیجه با آخرین نرخ دریافتی محاسبه شده است.','A new rate is unavailable; the result uses the last received rate.','Yeni kur kullanılamıyor; sonuç son alınan kurla hesaplandı.')[lang]}</p>}
 <div className="intl-iran-rate"><h4>{T('دلار در بازار آزاد ایران','US dollar in Iran’s open market','İran serbest piyasasında ABD doları')[lang]}</h4>{iranAvailable?<><strong dir="ltr">1 USD = {format(rates!.iran!.rate)} IRR</strong><p>{format(rates!.iran!.rate/10)} {T('تومان برای هر دلار','toman per US dollar','ABD doları başına tümen')[lang]}</p><small>{T('زمان قیمت در منبع:','Source quote time:','Kaynak fiyat zamanı:')[lang]} {new Date(rates!.iran!.updatedAt).toLocaleString(locale)} · {T('آخرین بررسی:','Last checked:','Son kontrol:')[lang]} {new Date(rates!.iran!.checkedAt).toLocaleTimeString(locale)}</small>{Date.now()-rates!.iran!.updatedAt>6*3600000&&<p>{T('آخرین قیمت منتشرشده؛ منبع هنوز قیمت جدیدی ارائه نکرده است.','Latest published quote; the source has not yet provided a newer price.','Son yayımlanan fiyat; kaynak henüz yeni fiyat vermedi.')[lang]}</p>}</>:<p role="status">{T('نرخ بازار آزاد ایران موقتاً در دسترس نیست.','Iran’s open-market rate is temporarily unavailable.','İran serbest piyasa kuru geçici olarak kullanılamıyor.')[lang]}</p>}<a href="https://www.tgju.org/profile/price_dollar_rl" target="_blank" rel="noopener noreferrer">{T('منبع: شبکهٔ اطلاع‌رسانی طلا و ارز (TGJU)','Source: TGJU','Kaynak: TGJU')[lang]}</a><p>{T('بررسی خودکار هر ۶۰ ثانیه؛ در تعطیلی بازار، آخرین قیمت منتشرشده با زمان اصلی آن نمایش داده می‌شود.','Automatically checked every 60 seconds; when the market is closed, the latest published quote retains its original timestamp.','Her 60 saniyede otomatik kontrol; piyasa kapalıyken son fiyat özgün zamanıyla gösterilir.')[lang]}</p></div>
 <p className="intl-rate-source">{rates?.updatedAt&&<>{T('زمان نرخ مرجع:','Reference rate updated:','Referans kur zamanı:')[lang]} {new Date(rates.updatedAt).toLocaleString(locale)} · </>}<a href="https://www.exchangerate-api.com" target="_blank" rel="noopener noreferrer">Rates By Exchange Rate API</a></p><p className="intl-rate-note">{T('نرخ مرجع ماشین‌حساب روزانه به‌روزرسانی می‌شود و نرخ لحظه‌ای معامله نیست. کارمزد در محاسبه لحاظ نشده است. IRR ریال ایران است؛ ۱۰ ریال = ۱ تومان. نرخ IRR از بازار آزاد ایران گرفته می‌شود؛ تبدیل آن به ارزهای دیگر با نرخ مرجع همان ارز محاسبه می‌شود. نرخ نهایی حواله را استعلام کنید.','Calculator reference rates update daily and are not real-time transaction quotes. Fees are excluded. IRR is Iranian rial; 10 rial = 1 toman. IRR uses Iran’s open-market quote; cross-currency conversions also use the other currency’s reference rate. Request a final transfer quote.','Hesaplayıcının referans kurları günlük güncellenir; anlık işlem teklifi değildir. Ücretler dahil değildir. IRR İran riyalidir; 10 riyal = 1 tümen. IRR İran serbest piyasa fiyatını kullanır; çapraz dönüşümlerde diğer para biriminin referans kuru da kullanılır. Nihai transfer teklifini isteyin.')[lang]}</p></div></section>;
}
