'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeftRight,RefreshCw} from 'lucide-react';
import type {Language} from './content';
import {T} from './international-data';
const currencies=['USD','EUR','GBP','TRY','AED','CNY','RUB','CHF','CAD','AUD','JPY','SAR','IRR'];
type Rates={rates:Record<string,number>;updatedAt:number;nextUpdateAt:number|null};
export default function ExchangeOnline({lang}:{lang:Language}){
 const host=useRef<HTMLDivElement>(null);const [rates,setRates]=useState<Rates|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(false),[amount,setAmount]=useState('1000'),[from,setFrom]=useState('USD'),[to,setTo]=useState('TRY');
 const locale=lang==='fa'?'fa-IR':lang==='tr'?'tr-TR':'en-GB';
 const refresh=useCallback(async(signal?:AbortSignal)=>{setBusy(true);try{const r=await fetch('/api/exchange-rates',{signal});if(!r.ok)throw Error();const d=await r.json() as Rates;setRates(d);setError(false);}catch{if(!signal?.aborted)setError(true);}finally{if(!signal?.aborted)setBusy(false);}},[]);
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=setInterval(()=>void refresh(controller.signal),300000);return()=>{controller.abort();clearInterval(timer);};},[refresh]);
 useEffect(()=>{const container=host.current;if(!container)return;const widget=document.createElement('tv-forex-table');widget.setAttribute('currencies',['USD','EUR','GBP','TRY','CHF','JPY','CAD','AUD'].join(','));widget.setAttribute('theme','light');widget.style.cssText='display:block;width:100%;height:500px;';container.appendChild(widget);if(!document.querySelector('script[data-creator-forex]')){const script=document.createElement('script');script.type='module';script.src='https://widgets.tradingview-widget.com/w/en/tv-forex-table.js';script.dataset.creatorForex='true';document.head.appendChild(script);}return()=>{widget.remove();};},[]);
 const n=Number(amount),valid=amount.trim()!==''&&Number.isFinite(n)&&n>=0&&n<=1e12;
 const rate=rates?rates.rates[to]/rates.rates[from]:null;
 const stale=!!rates&&(error||Date.now()-rates.updatedAt>172800000);
 const format=(v:number)=>new Intl.NumberFormat(locale,{maximumFractionDigits:6}).format(v);
 return <section className="intl-exchange-online" aria-labelledby="online-exchange-title"><div className="intl-exchange-heading"><div><span className="intl-eyebrow">{T('بازار ارز آنلاین','Currency market online','Çevrim içi döviz piyasası')[lang]}</span><h2 id="online-exchange-title">{T('نرخ ارز و تبدیل آنلاین','Exchange rates & online conversion','Döviz kurları ve çevrim içi dönüşüm')[lang]}</h2></div><span className="intl-rate-tag">{T('دادهٔ آنلاین','Online data','Çevrim içi veri')[lang]}</span></div>
 <p>{T('جدول بازار با داده‌های TradingView به‌روزرسانی می‌شود. در تعطیلی بازار یا بسته به منبع، آخرین نرخ موجود نمایش داده می‌شود.','The market table updates with TradingView data. When markets are closed, or depending on the feed, it shows the latest available quote.','Piyasa tablosu TradingView verileriyle güncellenir. Piyasa kapalıyken veya veri kaynağına göre son mevcut fiyat gösterilir.')[lang]}</p>
 <div className="intl-forex-scroll" dir="ltr"><div ref={host} className="intl-forex-widget"/></div><p className="intl-rate-source"><a href="https://www.tradingview.com/markets/currencies/" target="_blank" rel="noopener noreferrer">{T('مشاهدهٔ بازار ارز در TradingView','View currency markets on TradingView','TradingView döviz piyasalarını aç')[lang]}</a></p>
 <div className="intl-currency-calculator"><div className="intl-exchange-heading"><h3>{T('محاسبهٔ تبدیل ارز','Currency converter','Döviz hesaplayıcı')[lang]}</h3><button type="button" className="intl-rate-refresh" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16}/>{T('به‌روزرسانی','Refresh','Yenile')[lang]}</button></div><div className="intl-converter-inputs"><label>{T('مبلغ','Amount','Tutar')[lang]}<input type="number" dir="ltr" min="0" max="1000000000000" step="any" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>{T('از ارز','From','Kaynak')[lang]}<select value={from} onChange={e=>setFrom(e.target.value)} dir="ltr">{currencies.map(c=><option key={c} value={c}>{c}</option>)}</select></label><button className="intl-currency-swap" type="button" aria-label={T('جابه‌جایی ارزها','Swap currencies','Para birimlerini değiştir')[lang]} onClick={()=>{setFrom(to);setTo(from);}}><ArrowLeftRight size={20}/></button><label>{T('به ارز','To','Hedef')[lang]}<select value={to} onChange={e=>setTo(e.target.value)} dir="ltr">{currencies.map(c=><option key={c} value={c}>{c}</option>)}</select></label></div>
 <div className="intl-converter-result" aria-live="polite">{!rates?<p>{busy?T('دریافت نرخ‌ها…','Loading rates…','Kurlar yükleniyor…')[lang]:T('نرخ‌ها موقتاً در دسترس نیستند؛ دوباره تلاش کنید.','Rates are temporarily unavailable. Please retry.','Kurlar geçici olarak kullanılamıyor. Yeniden deneyin.')[lang]}</p>:!valid?<p>{T('یک مبلغ معتبر وارد کنید.','Enter a valid amount.','Geçerli bir tutar girin.')[lang]}</p>:<><strong dir="ltr">{format(n*rate!)} {to}</strong><span dir="ltr">1 {from} = {format(rate!)} {to}</span></>}</div>
 {stale&&<p role="alert" className="intl-form-error">{T('نرخ جدید در دسترس نیست؛ نتیجه با آخرین نرخ دریافتی محاسبه شده است.','A new rate is unavailable; the result uses the last received rate.','Yeni kur kullanılamıyor; sonuç son alınan kurla hesaplandı.')[lang]}</p>}
 <p className="intl-rate-source">{rates&&<>{T('زمان نرخ مرجع:','Reference rate updated:','Referans kur zamanı:')[lang]} {new Date(rates.updatedAt).toLocaleString(locale)} · </>}<a href="https://www.exchangerate-api.com" target="_blank" rel="noopener noreferrer">Rates By Exchange Rate API</a></p><p className="intl-rate-note">{T('نرخ مرجع ماشین‌حساب روزانه به‌روزرسانی می‌شود و نرخ لحظه‌ای معامله نیست. کارمزد در محاسبه لحاظ نشده است. IRR ریال ایران است، نه تومان؛ نرخ مرجع آن نرخ بازار آزاد ایران نیست. نرخ نهایی حواله را استعلام کنید.','Calculator reference rates update daily and are not real-time transaction quotes. Fees are excluded. IRR means Iranian rial, not toman; its reference rate is not the Iranian open-market rate. Request a final transfer quote.','Hesaplayıcının referans kurları günlük güncellenir; anlık işlem teklifi değildir. Ücretler dahil değildir. IRR İran riyalidir, tümen değildir; referans kuru İran serbest piyasa kuru değildir. Nihai transfer teklifini isteyin.')[lang]}</p></div></section>;
}
