'use client';
import {useEffect,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {ArrowRight,ChevronLeft,ChevronRight,Compass,GraduationCap,ShieldCheck,ClipboardCheck,ChartNoAxesCombined,Globe2} from 'lucide-react';
import type {Language} from './content';
import {T} from './international-data';
import {earthDestinations} from '@/lib/earth-destinations';
import './home-experience.css';
const Earth=dynamic(()=>import('./interactive-earth'),{ssr:false,loading:()=> <div className="cg-earth-loading"><Globe2 size={52}/></div>});
type Preview={slug:string;name:Record<Language,string>;image:string;city:Record<Language,string>;countryCode:string;programmeCount:number;fields:Record<Language,string>[];languages:string[]};
const landmarks:Record<string,Record<Language,string>>={TR:T('استانبول','Istanbul','İstanbul'),DE:T('برلین','Berlin','Berlin'),NL:T('آمستردام','Amsterdam','Amsterdam'),CY:T('بندر پافوس','Paphos Harbour','Baf Limanı'),CN:T('دیوار بزرگ چین','Great Wall of China','Çin Seddi'),RU:T('مسکو','Moscow','Moskova'),ES:T('مادرید','Madrid','Madrid')};
const steps=[{icon:Compass,title:T('انتخاب کشور','Choose country','Ülke seç'),note:T('مقصدت را بشناس','Find your destination','Ülkeni keşfet'),href:'countries'},{icon:GraduationCap,title:T('کشف دانشگاه‌ها','Explore universities','Üniversiteleri keşfet'),note:T('رشته‌ها را مقایسه کن','Compare programmes','Programları karşılaştır'),href:'universities'},{icon:ShieldCheck,title:T('بررسی شرایط','Check eligibility','Uygunluğunu kontrol et'),note:T('ارزیابی اختصاصی بگیر','Get personal guidance','Kişisel danışmanlık al'),href:'match'},{icon:ClipboardCheck,title:T('شروع درخواست','Start application','Başvuruya başla'),note:T('مسیرت را بساز','Build your journey','Yolculuğunu oluştur'),href:'explore#build-journey'},{icon:ChartNoAxesCombined,title:T('پیگیری پذیرش','Track admission','Başvurunu takip et'),note:T('از پیشرفتت باخبر باش','Follow your progress','İlerlemeni takip et'),href:'journey'}];
export default function HomeExperience({lang}:{lang:Language}){
 const [code,setCode]=useState('TR'),[universities,setUniversities]=useState<Preview[]>([]),[loaded,setLoaded]=useState(false),[failed,setFailed]=useState(false),[city,setCity]=useState('all');const carousel=useRef<HTMLDivElement>(null);
 useEffect(()=>{const abort=new AbortController();fetch('/api/universities?discovery=1',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<{universities:Preview[]}>;}).then(d=>{setUniversities(d.universities);setLoaded(true);}).catch(()=>{if(!abort.signal.aborted)setFailed(true);});return()=>abort.abort();},[]);
 const destination=earthDestinations.find(d=>d.code===code)!;const available=universities.filter(u=>u.countryCode===code);const cities=[...new Set(available.map(u=>u.city.en))];const shown=available.filter(u=>city==='all'||u.city.en===city).sort((a,b)=>Number(b.slug==='istanbul-atlas-university')-Number(a.slug==='istanbul-atlas-university')||b.programmeCount-a.programmeCount).slice(0,3);const programmeCount=universities.reduce((n,u)=>n+u.programmeCount,0);
 function select(next:string){setCode(next);setCity('all');}
 const countryHref=`/${lang}/countries/${destination.slug}`;
 return <section className="cg-experience" dir={lang==='fa'?'rtl':'ltr'} aria-label={T('آغاز مسیر تحصیل بین‌المللی','Your international student journey','Uluslararası öğrenci yolculuğun')[lang]}>
  <div className="cg-main-world"><div className="cg-world-backdrop"><Earth lang={lang} nightView selectedCode={code} onSelect={select} destinations={earthDestinations.map(d=>({...d,universityCount:loaded?universities.filter(u=>u.countryCode===d.code).length:undefined}))}/></div>
   <div className="cg-world-copy"><span className="cg-eyebrow">{T('همراه تو در مسیر تحصیل جهانی','YOUR GLOBAL EDUCATION PARTNER','KÜRESEL EĞİTİM YOLCULUĞUNDA YANINDA')[lang]}</span><h1>{T('از رویاها','From Dreams','Hayallerden')[lang]}<br/><em>{T('تا دانشگاه‌های','to Universities','Üniversitelere')[lang]}</em><br/>{T('سراسر جهان','Worldwide','Dünya Çapında')[lang]}</h1><p>{T('پذیرش دانشگاه، اقامت، پرواز، ویزا و همراهی در تمام مسیر — در یک پلتفرم.','University admission, accommodation, flights, visa and support through your journey — all in one platform.','Üniversite kabulü, konaklama, uçuş, vize ve yolculuğun boyunca destek — tek bir platformda.')[lang]}</p><div className="cg-actions"><a className="cg-primary" href={`/${lang}/explore#build-journey`}>{T('مسیرت را شروع کن','Start Your Journey','Yolculuğuna başla')[lang]}<ArrowRight size={18}/></a><a className="cg-secondary" href={`/${lang}/countries`}><Compass size={19}/>{T('کشف جهان','Explore the World','Dünyayı keşfet')[lang]}</a></div>
    <dl className="cg-stats"><div><dt>{loaded?universities.length:'—'}</dt><dd>{T('دانشگاه در فهرست','Catalogue universities','Katalog üniversitesi')[lang]}</dd></div><div><dt>{earthDestinations.length}</dt><dd>{T('راهنمای کشور','Country guides','Ülke rehberi')[lang]}</dd></div><div><dt>{loaded?programmeCount:'—'}</dt><dd>{T('رشتهٔ ثبت‌شده','Recorded programmes','Kayıtlı program')[lang]}</dd></div><div><dt>3</dt><dd>{T('زبان پلتفرم','Platform languages','Platform dili')[lang]}</dd></div></dl>
   </div>
   <nav className="cg-journey-steps" aria-label={T('گام‌های مسیر دانشجو','Student journey steps','Öğrenci yolculuğu adımları')[lang]}>{steps.map((step,i)=><a key={step.href} href={`/${lang}/${step.href}`}><step.icon size={21}/><div><span className="cg-step-number">{i+1}</span><strong>{step.title[lang]}</strong></div><small>{step.note[lang]}</small></a>)}</nav>
   <div className="cg-country-carousel"><button className="cg-carousel-arrow" aria-label={T('مقصدهای قبلی','Previous destinations','Önceki ülkeler')[lang]} onClick={()=>carousel.current?.scrollBy({left:lang==='fa'?330:-330,behavior:'smooth'})}><ChevronLeft size={18}/></button><div ref={carousel} className="cg-country-track">{earthDestinations.map(d=><button key={d.code} aria-pressed={d.code===code} onClick={()=>select(d.code)}><img className="cg-country-photo" src={`/images/destinations/${d.code.toLowerCase()}.webp`} alt={landmarks[d.code][lang]} width={350} height={220} loading="lazy"/><div><img src={`/flags/${d.code.toLowerCase()}.svg`} alt="" width={28} height={20}/><span><strong>{d.name[lang]}</strong><small>{loaded&&universities.some(u=>u.countryCode===d.code)?`${universities.filter(u=>u.countryCode===d.code).length} ${T('دانشگاه ثبت‌شده','catalogue universities','katalog üniversitesi')[lang]}`:T('راهنمای تحصیل و زندگی','Study & living guide','Eğitim ve yaşam rehberi')[lang]}</small></span></div></button>)}</div><button className="cg-carousel-arrow" aria-label={T('مقصدهای بعدی','Next destinations','Sonraki ülkeler')[lang]} onClick={()=>carousel.current?.scrollBy({left:lang==='fa'?-330:330,behavior:'smooth'})}><ChevronRight size={18}/></button></div>
  </div>
  <aside className="cg-destination-panel" aria-label={T('مقصد انتخاب‌شده','Selected destination','Seçilen ülke')[lang]}><div className="cg-destination-cover"><img className="cg-cover-image" src={`/images/destinations/${code.toLowerCase()}.webp`} alt={landmarks[code][lang]} width={1400} height={850} fetchPriority="high"/><div className="cg-destination-top"><img src={`/flags/${code.toLowerCase()}.svg`} alt="" width={43} height={31}/><div><h2>{destination.name[lang]}</h2><p>{loaded?(available.length?`${available.length} ${T('دانشگاه در فهرست ما','universities in our catalogue','kataloğumuzda üniversite')[lang]}`:T('راهنمای کشور با منابع رسمی','Country guide with official sources','Resmî kaynaklarla ülke rehberi')[lang]):T('در حال دریافت اطلاعات…','Loading catalogue…','Katalog yükleniyor…')[lang]}</p></div><a href={countryHref}>{T('کشف مقصد','Explore','Keşfet')[lang]}<ArrowRight size={15}/></a></div><span className="cg-landmark">{landmarks[code][lang]}</span></div>
   <div className="cg-city-tabs" aria-label={T('فیلتر شهر','Filter by city','Şehre göre filtrele')[lang]}><button aria-pressed={city==='all'} onClick={()=>setCity('all')}>{T('همهٔ دانشگاه‌ها','All universities','Tüm üniversiteler')[lang]}</button>{cities.map(c=><button key={c} aria-pressed={city===c} onClick={()=>setCity(c)}>{available.find(u=>u.city.en===c)?.city[lang]}</button>)}</div>
   <div className="cg-university-list" aria-live="polite">{shown.map(u=><article key={u.slug} className="cg-university-preview"><a href={`/${lang}/universities/${u.slug}`}><img src={u.image} alt={u.name[lang]} width={210} height={160} loading="lazy"/></a><div><h3><a href={`/${lang}/universities/${u.slug}`}>{u.name[lang]}</a></h3><small>{u.city[lang]} · {destination.name[lang]}</small><p>{u.fields.length?u.fields.map(f=>f[lang]).join(' · '):T('رشته‌ها و شهریه در لیست اصلی دانشگاه','Programmes & tuition in the original schedule','Program ve ücretler orijinal listede')[lang]}</p><a className="cg-view-university" href={`/${lang}/universities/${u.slug}`}>{T('دیدن دانشگاه','View university','Üniversiteyi gör')[lang]}<ArrowRight size={13}/></a></div></article>)}{!shown.length&&<div className="cg-country-guide"><Globe2 size={34}/><h3>{loaded?T('مقصدت را بهتر بشناس','Get to know your destination','Ülkeni daha iyi tanı')[lang]:T('دانشگاه‌ها در حال بارگذاری‌اند','Loading universities','Üniversiteler yükleniyor')[lang]}</h3><p>{loaded?T('هنوز دانشگاهی برای این کشور در فهرست سایت منتشر نشده است. شرایط تحصیل، ویزا، زندگی و ورود را با منابع رسمی بررسی کن.','No university records are published for this country yet. Explore education, visa, living and arrival guidance with official sources.','Bu ülke için henüz üniversite kaydı yayımlanmadı. Resmî kaynaklarla eğitim, vize, yaşam ve varış rehberini keşfet.')[lang]:failed?T('دریافت فهرست انجام نشد؛ فهرست دانشگاه‌ها را باز کنید.','The catalogue could not load; open the university list.','Katalog yüklenemedi; üniversite listesini açın.')[lang]:T('اطلاعات واقعی فهرست دانشگاه‌های سایت','Real data from our university catalogue','Üniversite kataloğumuzdaki gerçek veriler')[lang]}</p><a href={countryHref}>{T('راهنمای این کشور','Explore country guide','Ülke rehberini keşfet')[lang]}<ArrowRight size={15}/></a><a href={`/${lang}/consultation?country=${destination.slug}`}>{T('ارزیابی شرایط من','Assess my options','Seçeneklerimi değerlendir')[lang]}</a></div>}</div>
   <a className="cg-view-all" href={available.length?`/${lang}/universities?country=${code}`:countryHref}>{available.length?T('دیدن همهٔ دانشگاه‌های این مقصد','View all universities in this destination','Bu ülkedeki tüm üniversiteleri gör')[lang]:T('دیدن راهنمای کامل مقصد','View the full destination guide','Ülke rehberinin tamamını gör')[lang]}<ArrowRight size={16}/></a>
  </aside>
  <details className="cg-photo-credits"><summary>{T('منابع تصاویر','Image credits','Görsel kaynakları')[lang]}</summary><p>Destination photographs: Unsplash · <a href="https://unsplash.com/license" target="_blank" rel="noopener noreferrer">Unsplash License</a>. Paphos: <a href="https://commons.wikimedia.org/wiki/File:Paphos_Harbour_6590.jpg" target="_blank" rel="noopener noreferrer">Anna Anichkova</a> · <a href="https://creativecommons.org/licenses/by-sa/3.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 3.0</a>. Moscow: <a href="https://commons.wikimedia.org/wiki/File:Saint_Basil%27s_Cathedral_in_Moscow.jpg" target="_blank" rel="noopener noreferrer">Tsy1980</a> · <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener noreferrer">CC BY-SA 4.0</a>. Resized, compressed and displayed with cropping. These two adapted images remain under their respective licenses. University photographs: see each university page.</p></details>
 </section>;
}
