import {T,ui,services,type Text,type Service} from './international-data';
import {countries} from './international-countries';
import {universities,priceTitle,priceDescription} from './university-price-data';
import {articles} from './international-articles';
export const dentistry:Service={...services.find(s=>s.slug==='medical')!,slug:'medical/dentistry',title:T('دندان‌پزشکی','Dental care coordination','Diş sağlığı koordinasyonu'),short:T('لبخند شما، با ارزیابی تخصصی.','Your smile, with a clinical perspective.','Gülümsemeniz, uzman değerlendirmesiyle.'),description:T('برای بررسی درمان‌های دندان‌پزشکی، مدارک موجود و نیاز شما با رضایت‌تان برای هماهنگی ارزیابی تخصصی ثبت می‌شود. طرح درمان، مدت و هزینهٔ نهایی پس از معاینهٔ دندان‌پزشک و بررسی تصویربرداری مشخص می‌شوند.','Share existing records and needs with consent to coordinate a professional dental assessment. Final treatment, duration and cost depend on examination and imaging review.','Uzman diş değerlendirmesinin koordinasyonu için mevcut belgelerinizi ve ihtiyacınızı onayınızla paylaşın. Nihai plan, süre ve maliyet muayene ve görüntüleme değerlendirmesine bağlıdır.'),items:[T('ایمپلنت','Implants','İmplant'),T('لمینت و کامپوزیت','Veneers and composite bonding','Laminate ve kompozit'),T('ارتودنسی','Orthodontics','Ortodonti'),T('درمان ریشه','Root canal treatment','Kanal tedavisi'),T('ترمیم','Restorative care','Restoratif bakım'),T('سفیدکردن دندان','Whitening','Beyazlatma'),T('طراحی لبخند','Smile planning','Gülüş planlaması'),T('هماهنگی مراقبت پس از درمان','Aftercare coordination','Tedavi sonrası bakım')]};
export const treatment:Service={...services.find(s=>s.slug==='medical')!,slug:'medical/treatment',title:T('هماهنگی درمان و پیگیری','Treatment & follow-up coordination','Tedavi ve takip koordinasyonu'),short:T('از بررسی اولیه تا مراقبت بعدی.','From initial review to aftercare.','İlk değerlendirmeden sonraki bakıma.'),description:T('هماهنگی دریافت نظر پزشک، بررسی اولیهٔ مدارک، برنامهٔ سفر، اقامت و پیگیری؛ هر مرحله باید با نیاز بیمار و توصیهٔ مرکز درمان تطبیق داشته باشد. هماهنگی اجرایی جایگزین تصمیم بالینی نیست.','Coordinate clinical opinions, initial records, travel, accommodation and follow-up. Each stage must fit the patient’s needs and provider advice. Administrative coordination is not a clinical decision.','Hekim görüşü, ilk belgeler, seyahat, konaklama ve takibi koordine edin. Her aşama hastanın ihtiyaçlarına ve merkez görüşüne uymalıdır. İdari koordinasyon klinik karar değildir.'),items:[T('زیبایی و بررسی تخصصی','Aesthetics consultation','Estetik değerlendirmesi'),T('چشم و ارتوپدی','Eyes and orthopaedics','Göz ve ortopedi'),T('قلب و زنان','Cardiology and gynaecology','Kardiyoloji ve kadın sağlığı'),T('ناباروری','Fertility care inquiries','Üreme sağlığı talepleri'),T('چکاپ و بررسی پیشگیرانه','Check-up coordination','Check-up koordinasyonu'),T('پیگیری و مدارک پس از درمان','Follow-up and discharge records','Takip ve taburcu belgeleri')]};
export const allDetailServices=[...services,dentistry,treatment];
export const pageDefinitions:{[path:string]:{title:Text;description:Text}}={
 'university-prices':{title:priceTitle,description:priceDescription},
 'international-services':{title:ui.international,description:ui.servicesSubtitle},
 about:{title:ui.about,description:T('خدمات بین‌المللی را با هماهنگی، شفافیت و ارتباط چندزبانه کنار هم می‌آوریم.','Connecting international services through coordination, clarity and multilingual communication.','Uluslararası hizmetleri koordinasyon, şeffaflık ve çok dilli iletişimle bir araya getiriyoruz.')},
 contact:{title:ui.contact,description:T('برای شروع گفتگو، درخواست خود را ثبت کنید؛ اطلاعات رسمی تماس پس از تأیید اعلام می‌شود.','Submit an inquiry to start a conversation; verified contact details will be announced.','Görüşme başlatmak için talep gönderin; doğrulanmış iletişim bilgileri açıklanacaktır.')},
 consultation:{title:ui.consult,description:ui.finalDesc},'track-request':{title:ui.track,description:T('وضعیت درخواست را با کد پیگیری و کلید خصوصی بررسی کنید.','Check your request using its tracking code and private key.','Takip kodu ve özel anahtarla talep durumunu kontrol edin.')},
 faq:{title:ui.faq,description:T('پاسخ روشن به پرسش‌های تحصیل، پرداخت، سفر، درمان، بیمه و اقامت.','Clear answers on study, payments, travel, healthcare, insurance and residency.','Eğitim, ödeme, seyahat, sağlık, sigorta ve oturum için açık yanıtlar.')},
 blog:{title:ui.blog,description:T('راهنماهای کاربردی برای تصمیم‌های آگاهانه‌تر در مسیرهای بین‌المللی.','Practical guides for better-informed international decisions.','Uluslararası kararlar için pratik rehberler.')},
 privacy:{title:ui.privacy,description:T('اطلاعاتی که دریافت می‌کنیم، هدف پردازش و روش حفاظت از درخواست و مدارک شما.','Information we collect, processing purposes and protection of your requests and documents.','Topladığımız bilgiler, işleme amaçları ve talep ve belgelerin korunması.')},
 terms:{title:ui.terms,description:T('حدود خدمات، شرایط درخواست، مسئولیت تأمین‌کنندگان و نحوهٔ توافق پیش از اقدام.','Service boundaries, inquiry terms, provider responsibilities and agreement before action.','Hizmet sınırları, talep koşulları, sağlayıcı sorumlulukları ve işlem öncesi anlaşma.')},
};
export function resolvePage(path:string){const university=universities.find(u=>path===`university-prices/${u.slug}`);if(university)return{title:university.name,description:priceDescription,type:'university-prices',university};if(!path)return{title:ui.heroSubtitle,description:ui.intro,type:'home'};const service=allDetailServices.find(s=>s.slug===path);if(service)return{title:service.title,description:service.description,type:'service',service};const country=countries.find(c=>`study-abroad/${c.slug}`===path);if(country)return{title:T(`تحصیل در ${country.name.fa}`,`Study in ${country.name.en}`,`${country.name.tr}’da eğitim`),description:country.intro,type:'country',country};const article=articles.find(a=>`blog/${a.slug}`===path);if(article)return{title:article.title,description:article.summary,type:'article',article};const page=pageDefinitions[path];if(page)return{...page,type:path};return null;}
export const intlPaths=[...Object.keys(pageDefinitions),...universities.map(u=>`university-prices/${u.slug}`),...allDetailServices.map(s=>s.slug),...countries.map(c=>`study-abroad/${c.slug}`),...articles.map(a=>`blog/${a.slug}`)];
export const policySections={privacy:[
 {title:T('اطلاعات دریافتی و هدف استفاده','Information and purpose','Bilgi ve amaç'),body:T('فرم‌ها نام، تماس، خدمت، مقصد و اطلاعات لازم برای ارزیابی درخواست را دریافت می‌کنند. این داده‌ها برای پاسخ، هماهنگی و پیگیری همان درخواست استفاده می‌شوند. اطلاعات غیرضروری، رمز، کلید کیف پول و مدارک هویتی را در توضیحات ارسال نکنید.','Forms collect your name, contact details, service, destination and information needed to assess your inquiry. They are used to respond, coordinate and track that request. Do not send unnecessary information, passwords, wallet keys or identity documents in free text.','Formlar ad, iletişim, hizmet, hedef ve talebi değerlendirmek için gereken bilgileri toplar. Yanıt, koordinasyon ve takip için kullanılır. Açıklamaya gereksiz bilgi, parola, cüzdan anahtarı veya kimlik belgesi göndermeyin.')},
 {title:T('رضایت و مدارک پزشکی','Consent and medical records','Onay ve tıbbi belgeler'),body:T('ارسال فرم با رضایت شما انجام می‌شود. بارگذاری پزشکی اختیاری و دارای رضایت مستقل است. فقط PDF، JPEG و PNG در محدودهٔ اعلام‌شده پذیرفته می‌شوند و فایل‌ها لینک عمومی ندارند. پیش از اشتراک پرونده با مرکز درمان، مقصد و هدف اشتراک باید با شما روشن شود.','Forms require your consent. Medical uploads are optional with separate consent. Only PDF, JPEG and PNG within stated limits are accepted, with no public file links. The recipient and purpose must be clarified before records are shared with a provider.','Formlar onay gerektirir. Tıbbi yükleme isteğe bağlı ve ayrı onaylıdır. Belirtilen sınırda PDF, JPEG ve PNG kabul edilir; açık dosya bağlantısı yoktur. Sağlayıcıyla paylaşmadan önce alıcı ve amacı netleştirilmelidir.')},
 {title:T('نگهداری و امنیت','Storage and security','Saklama ve güvenlik'),body:T('درخواست‌ها در پایگاه داده و فایل‌ها در فضای خصوصی نگهداری می‌شوند. کلید پیگیری به‌صورت هش ذخیره می‌شود و برای مشاهدهٔ وضعیت لازم است. دسترسی به پرونده باید به افراد مجاز محدود بماند. برنامهٔ دقیق نگهداری و حذف داده‌های شرکت پیش از شروع عملیات عمومی اعلام خواهد شد.','Requests are stored in a database and files in private storage. Tracking keys are stored as hashes and required to view status. Case access must remain restricted to authorised staff. The company’s specific retention and deletion schedule will be published before public operations.','Talepler veritabanında, dosyalar özel alanda tutulur. Takip anahtarları özet olarak saklanır ve durum için gerekir. Dosya erişimi yetkili kişilerle sınırlı olmalıdır. Şirketin saklama ve silme takvimi genel operasyon öncesi açıklanacaktır.')},
 {title:T('حقوق و ارتباط','Your choices and contact','Haklar ve iletişim'),body:T('برای اصلاح اطلاعات، پس‌گرفتن رضایت یا درخواست حذف، از فرم تماس استفاده کنید و کد پرونده را درج کنید؛ کلید خصوصی را در توضیحات نفرستید. ممکن است نگهداری بخشی از سوابق طبق قانون لازم باشد. اطلاعات مسئول حقوقی و نشانی رسمی پس از تأیید در صفحهٔ تماس قرار می‌گیرد.','Use the contact form to request corrections, withdraw consent or request deletion, including the case code but not the private key. Some records may need retention under applicable law. Verified legal-entity and contact details will be listed on the contact page.','Düzeltme, onayı geri çekme veya silme için iletişim formunu kullanın; dosya kodunu ekleyin, özel anahtarı yazmayın. Bazı kayıtlar mevzuat gereği saklanabilir. Doğrulanmış tüzel kişi ve iletişim bilgileri iletişim sayfasında yer alacaktır.')},
 {title:T('کوکی و خدمات خارجی','Cookies and external services','Çerezler ve dış hizmetler'),body:T('این نسخه ابزار تبلیغاتی یا تحلیل بازدید اضافه نمی‌کند. میزبانی خصوصی ممکن است برای ورود و امنیت از کوکی ضروری استفاده کند. لینک به منابع رسمی شما را به وب‌سایت مستقل می‌برد که سیاست خود را دارد. اگر ابزار غیرضروری اضافه شود، انتخاب رضایت باید پیش از استفاده فراهم شود.','This version adds no advertising or analytics tools. Private hosting may use essential authentication and security cookies. Official-source links lead to independent sites with their own policies. Non-essential tools must offer consent choices before use.','Bu sürüm reklam veya analiz aracı eklemez. Özel barındırma temel giriş ve güvenlik çerezleri kullanabilir. Resmî kaynaklar kendi politikası olan bağımsız sitelerdir. Zorunlu olmayan araçlarda kullanım öncesi onay seçeneği sağlanmalıdır.')}
 ],terms:[
 {title:T('ماهیت درخواست و توافق','Inquiries and agreements','Talep ve anlaşmalar'),body:T('ثبت فرم تنها درخواست بررسی و ارتباط است و قرارداد، پذیرش دانشگاه، رزرو قطعی یا تأیید درمان ایجاد نمی‌کند. هر خدمت به توافق مستقل دربارهٔ دامنه، هزینه، تأمین‌کننده، زمان و شرایط لغو نیاز دارد.','Submission requests review and contact; it does not create a contract, admission, confirmed booking or treatment approval. Each service requires a separate agreement on scope, costs, provider, timing and cancellation.','Form inceleme ve iletişim talebidir; sözleşme, kabul, kesin rezervasyon veya tedavi onayı oluşturmaz. Her hizmet kapsam, ücret, sağlayıcı, süre ve iptal için ayrı anlaşma gerektirir.')},
 {title:T('تصمیم‌های رسمی و تخصصی','Official and professional decisions','Resmî ve uzman kararları'),body:T('پذیرش با دانشگاه، ویزا و اقامت با مراجع رسمی، درمان با پزشک و پوشش بیمه با بیمه‌گر است. هیچ نتیجه‌ای تضمین نمی‌شود. راهنمای سایت جایگزین مشاورهٔ حقوقی، پزشکی یا مالی متناسب با شرایط شخصی نیست.','Universities decide admission, authorities decide visas and residency, clinicians decide treatment, and insurers determine coverage. Outcomes are not guaranteed. Guides do not replace individual legal, medical or financial advice.','Kabul kurumun, vize ve oturum makamın, tedavi hekimin, teminat sigortacının kararıdır. Sonuç garantisi yoktur. Rehberler kişisel hukuki, tıbbi veya mali görüşün yerini almaz.')},
 {title:T('خدمات ارزی و دارایی دیجیتال','Currency and digital assets','Döviz ve dijital varlıklar'),body:T('این سایت تراکنش مالی اجرا نمی‌کند و نرخ زنده ندارد. خدمت عملیاتی نیازمند مجوز لازم، احراز هویت، رعایت محدودیت‌های قانونی و تأیید نرخ و کارمزد است. انتقال دارایی دیجیتال می‌تواند برگشت‌ناپذیر باشد و هیچ وعدهٔ سودی وجود ندارد.','This site does not execute financial transactions or display live rates. Execution requires relevant authorisation, identity checks, lawful availability and agreed quotes and fees. Crypto transfers may be irreversible and no returns are promised.','Site mali işlem yapmaz ve canlı kur göstermez. İşlem gerekli yetki, kimlik, yasal uygunluk ve onaylı kur ve ücret gerektirir. Kripto transferi geri alınamayabilir; getiri vaadi yoktur.')},
 {title:T('دقت اطلاعات و تعهدات متقاضی','Applicant information','Başvuru bilgileri'),body:T('اطلاعات باید صحیح و متعلق به شما یا با اختیار قانونی ارسال شوند. قبل از اقدام، قوانین روز، قرارداد تأمین‌کننده و شرایط مقصد را بررسی کنید. ارسال فایل مخرب، جعل مدارک، تبلیغات یا اطلاعات دیگران بدون رضایت مجاز نیست.','Provide accurate information belonging to you or submitted with lawful authority. Check current rules, provider terms and destination requirements before action. Malicious files, forged records, spam and unauthorised personal information are not permitted.','Doğru ve size ait veya yasal yetkiyle gönderilen bilgi sağlayın. İşlem öncesi güncel kural, sağlayıcı koşulu ve hedef şartını kontrol edin. Zararlı dosya, sahte belge, spam ve yetkisiz kişisel bilgi yasaktır.')},
 {title:T('اطلاعات شرکت و نسخهٔ شرایط','Company details and version','Şirket bilgileri ve sürüm'),body:T('نام حقوقی، مجوزها، نشانی و تأمین‌کنندگان تأییدشده هنوز اعلام نشده‌اند و باید پیش از شروع عملیات عمومی درج شوند. این نسخه برای ثبت درخواست اولیه و توسعهٔ سایت است؛ شرایط قرارداد نهایی جدا ارائه خواهد شد. نسخه: ۲ اکتبر ۲۰۲۶.','The legal entity, licences, address and verified providers have not yet been supplied and must be added before public operations. This version supports initial inquiries and site development; final contract terms will be provided separately. Version: 2 October 2026.','Tüzel kişi, ruhsat, adres ve doğrulanmış sağlayıcılar henüz verilmemiştir ve genel operasyon öncesi eklenmelidir. Bu sürüm ilk talep ve site geliştirme içindir; nihai sözleşme koşulları ayrıca sunulur. Sürüm: 2 Ekim 2026.')}
 ]};
