import {T,type Text} from './international-data';
export interface FAQ{category:string;q:Text;a:Text;}
export const faqs:FAQ[]=[
 {category:'general',q:T('از کجا شروع کنم؟','Where should I start?','Nereden başlamalıyım?'),a:T('خدمت و مقصد موردنظر را در فرم مشاوره مشخص کنید. پس از ثبت، کد پیگیری و کلید خصوصی دریافت می‌کنید؛ ارزیابی پرونده به اطلاعات کامل و شرایط ارائهٔ خدمت وابسته است.','Select a service and destination in the consultation form. You receive a tracking code and private key after submission; assessment depends on complete information and service availability.','Danışmanlık formunda hizmet ve hedefi seçin. Gönderim sonrası takip kodu ve özel anahtar alırsınız; değerlendirme tam bilgi ve hizmet uygunluğuna bağlıdır.')},
 {category:'general',q:T('آیا ثبت درخواست به معنی قرارداد است؟','Does a request create a contract?','Talep bir sözleşme oluşturur mu?'),a:T('خیر. فرم برای بررسی اولیه است. دامنهٔ خدمت، تأمین‌کننده، هزینه و شرایط پیش از هر تعهد یا پرداخت باید جداگانه و کتبی مشخص شوند.','No. Forms are for an initial review. Scope, provider, costs and terms must be agreed separately in writing before commitment or payment.','Hayır. Form ilk inceleme içindir. Taahhüt veya ödeme öncesi kapsam, sağlayıcı, maliyet ve koşullar ayrıca yazılı netleştirilir.')},
 {category:'study-abroad',q:T('آیا پذیرش یا ویزا تضمین می‌شود؟','Are admission or visas guaranteed?','Kabul veya vize garanti mi?'),a:T('خیر. دانشگاه دربارهٔ پذیرش و مرجع رسمی دربارهٔ ویزا تصمیم می‌گیرد. مدارک کامل می‌توانند به بررسی منظم کمک کنند، اما نتیجهٔ قطعی ایجاد نمی‌کنند.','No. Institutions decide admission and official authorities decide visas. Complete documents support an organised review but do not guarantee an outcome.','Hayır. Kabul kurumun, vize resmî makamın kararıdır. Tam belgeler düzenli değerlendirmeye yardımcı olur; sonucu garanti etmez.')},
 {category:'study-abroad',q:T('چه مدارکی برای ارزیابی اولیه لازم است؟','What is needed for an initial assessment?','İlk değerlendirme için ne gerekir?'),a:T('سن، آخرین مدرک، معدل، رشته، سطح زبان، مقصد و بودجهٔ تقریبی را اعلام کنید. ارسال گذرنامه یا مدارک حساس برای فرم اولیه لازم نیست؛ مدارک رسمی بعداً طبق درخواست دانشگاه مشخص می‌شوند.','Share age, highest qualification, grades, field, language level, destination and estimated budget. Sensitive documents are not needed for the initial form; official requirements follow the institution’s instructions.','Yaş, son diploma, not, alan, dil düzeyi, hedef ve yaklaşık bütçeyi paylaşın. İlk formda hassas belge gerekmez; resmî belgeler kurumun talimatına göre belirlenir.')},
 {category:'study-abroad',q:T('آیا می‌توان هزینه‌ها را با کار دانشجویی پوشش داد؟','Can student work cover all expenses?','Öğrenci işi tüm giderleri karşılar mı?'),a:T('روی درآمد قطعی حساب نکنید. اجازهٔ کار، ساعت مجاز و فرصت شغلی به وضعیت شما و مقررات روز بستگی دارد. بودجهٔ تحصیل باید مستقل از شغل تضمین‌نشده قابل تأمین باشد.','Do not assume guaranteed income. Work rights, hours and job availability depend on your status and current rules. Your study budget should not depend on unconfirmed employment.','Kesin gelir varsaymayın. Çalışma hakkı, saat ve iş fırsatı durumunuza ve güncel kurallara bağlıdır. Eğitim bütçesi kesinleşmemiş işe dayanmamalı.')},
 {category:'exchange',q:T('نرخ و کارمزد چگونه مشخص می‌شود؟','How are rates and fees determined?','Kur ve ücret nasıl belirlenir?'),a:T('پس از مشخص‌شدن ارز، مبلغ، کشورها و مسیر پرداخت، پیشنهاد نهایی بررسی می‌شود. جدول آنلاین نرخ بازار و ماشین‌حساب نرخ مرجع نمایش می‌دهد؛ مبلغ دریافتی و مجموع هزینه‌ها باید قبل از تأیید اعلام شوند.','After the currencies, amount, countries and route are known, a final quote can be reviewed. The online table shows market rates and the calculator reference rates; the received amount and total costs must be disclosed before confirmation.','Para birimleri, tutar, ülkeler ve yol belirlendikten sonra nihai teklif incelenir. Çevrim içi tablo piyasa, hesaplayıcı referans kurlarını gösterir; alınacak tutar ve toplam maliyet onaydan önce açıklanır.')},
 {category:'exchange',q:T('برای پرداخت شهریه چه اطلاعاتی لازم است؟','What is needed for a tuition payment?','Okul ücreti için ne gerekir?'),a:T('نام دانشگاه، صورتحساب رسمی، ارز و مبلغ و مهلت پرداخت باید بررسی شوند. اطلاعات حساب ذی‌نفع را فقط از کانال رسمی دانشگاه تأیید کنید و پیش از پرداخت هویت ارائه‌دهنده را بررسی کنید.','Review the institution, official invoice, currency, amount and deadline. Verify beneficiary details through the institution’s official channel and check the provider before paying.','Kurum, resmî fatura, para birimi, tutar ve son tarihi inceleyin. Alıcı bilgilerini kurumun resmî kanalından doğrulayın ve ödemeden önce sağlayıcıyı kontrol edin.')},
 {category:'crypto-exchange',q:T('اگر شبکه را اشتباه انتخاب کنم چه می‌شود؟','What if I choose the wrong network?','Yanlış ağ seçersem ne olur?'),a:T('ممکن است دارایی برای همیشه از دست برود و امکان بازیابی وجود نداشته باشد. دارایی، شبکه و نشانی دریافت را مستقل بررسی کنید؛ هزینهٔ شبکه نیز از کارمزد خدمت جداست.','Funds may be permanently lost with no recovery. Independently verify the asset, network and recipient address; network fees are separate from service fees.','Varlık geri dönüşsüz kaybolabilir. Varlık, ağ ve alıcı adresini ayrı doğrulayın; ağ ücreti hizmet ücretinden ayrıdır.')},
 {category:'crypto-exchange',q:T('آیا این سایت خرید یا انتقال را اجرا می‌کند؟','Does this website execute crypto transactions?','Bu site kripto işlemi yapar mı?'),a:T('خیر. فرم صرفاً استعلام است. انجام خدمت به احراز هویت، بررسی قانونی، دسترسی به تأمین‌کنندهٔ مجاز و تأیید شرایط نهایی وابسته است.','No. The form is an inquiry only. Service execution depends on identity and legal checks, an authorised provider and confirmation of final terms.','Hayır. Form yalnızca taleptir. İşlem kimlik ve mevzuat kontrolü, yetkili sağlayıcı ve nihai koşul onayına bağlıdır.')},
 {category:'hotel-reservation',q:T('آیا بعد از فرم، هتل قطعی رزرو می‌شود؟','Is the hotel booked after submitting?','Form sonrası otel kesin rezervasyon mu?'),a:T('خیر. ثبت فرم فقط درخواست رزرو است. موجودی، قیمت، شرایط لغو و پرداخت باید ابتدا تأیید شوند و سپس تأییدیهٔ رزرو صادر شود.','No. Submission is a reservation request. Availability, pricing, cancellation terms and payment must be confirmed before a booking confirmation is issued.','Hayır. Gönderim rezervasyon talebidir. Onay belgesinden önce uygunluk, fiyat, iptal koşulu ve ödeme doğrulanır.')},
 {category:'hotel-reservation',q:T('برای اقامت درمانی چه نکته‌ای مهم است؟','What matters for a medical stay?','Sağlık konaklamasında ne önemlidir?'),a:T('فاصله تا مرکز درمان، امکان همراه، دسترسی مناسب و انعطاف تاریخ را مشخص کنید. زمان سفر و نیازهای پس از درمان باید با نظر پزشک هماهنگ شوند.','Specify distance to the clinic, companion needs, accessibility and date flexibility. Travel timing and aftercare requirements should follow clinical advice.','Kliniğe mesafe, refakatçi, erişilebilirlik ve tarih esnekliğini belirtin. Seyahat zamanı ve bakım ihtiyaçları hekim görüşüne uygun olmalı.')},
 {category:'medical',q:T('آیا پیش از معاینه قیمت قطعی اعلام می‌شود؟','Can treatment prices be fixed before an examination?','Muayene öncesi kesin fiyat verilir mi?'),a:T('خیر. طرح و هزینهٔ نهایی به ارزیابی پزشک، آزمایش‌ها و شرایط بیمار وابسته است. برآورد اولیه جایگزین معاینه یا قرارداد درمان نیست.','No. Final plans and costs depend on clinical assessment, tests and the patient’s condition. An initial estimate is not an examination or treatment agreement.','Hayır. Nihai plan ve maliyet klinik değerlendirme, test ve hastanın durumuna bağlıdır. İlk tahmin muayene veya tedavi anlaşmasının yerini almaz.')},
 {category:'medical',q:T('مدارک پزشکی چگونه نگهداری می‌شوند؟','How are medical documents stored?','Tıbbi belgeler nasıl saklanır?'),a:T('بارگذاری اختیاری است و رضایت جداگانه می‌خواهد. فقط فایل‌های مجاز دریافت و در فضای خصوصی ذخیره می‌شوند؛ لینک دانلود عمومی وجود ندارد. برای بررسی اولیه از ارسال اطلاعات غیرضروری خودداری کنید.','Uploads are optional and require separate consent. Only allowed files are accepted in private storage, with no public download links. Avoid unnecessary sensitive information in the initial inquiry.','Yükleme isteğe bağlıdır ve ayrı onay gerekir. Yalnızca izin verilen dosyalar özel alanda saklanır; açık indirme bağlantısı yoktur. İlk talepte gereksiz hassas bilgi göndermeyin.')},
 {category:'insurance',q:T('آیا همهٔ هزینه‌های درمان تحت پوشش‌اند؟','Does insurance cover every medical expense?','Sigorta tüm tedavi giderlerini karşılar mı?'),a:T('خیر. پوشش به سقف تعهد، استثناها، بیماری‌های قبلی، فرانشیز و شرایط طرح وابسته است. متن بیمه‌نامه و شرایط خسارت را پیش از خرید مطالعه کنید.','No. Coverage depends on limits, exclusions, pre-existing conditions, deductibles and plan terms. Read the policy and claims conditions before purchasing.','Hayır. Teminat limit, istisna, önceki hastalık, muafiyet ve plan şartlarına bağlıdır. Satın almadan önce poliçe ve hasar koşullarını okuyun.')},
 {category:'insurance',q:T('بیمهٔ مناسب ویزا چگونه انتخاب می‌شود؟','How do I choose insurance for a visa?','Vize için sigorta nasıl seçilir?'),a:T('مدت، قلمرو و حداقل پوشش موردنیاز باید با دستورالعمل فعلی مرجع رسمی مقصد مطابقت داشته باشد. ارزان‌ترین طرح الزاماً مناسب درخواست شما نیست.','Duration, territory and required minimum cover must match current official destination guidance. The cheapest plan may not suit your application.','Süre, bölge ve asgari teminat güncel resmî hedef ülke rehberine uymalıdır. En ucuz plan başvurunuza uygun olmayabilir.')},
 {category:'residency',q:T('کدام مسیر اقامت برای من مناسب است؟','Which residency route fits me?','Hangi oturum yolu bana uygun?'),a:T('هدف، تابعیت، سابقهٔ تحصیل و کار، وضعیت خانواده و بودجه باید همراه با مقررات رسمی بررسی شود. یک مسیر واحد برای همه وجود ندارد و تصمیم نهایی با مرجع رسمی است.','Goals, nationality, education and work history, family situation and budget need review against official rules. No single route suits everyone; authorities decide the outcome.','Amaç, vatandaşlık, eğitim, iş, aile ve bütçe resmî kurallarla değerlendirilir. Herkese uygun tek yol yoktur; nihai karar makamlarındır.')},
];
export function serviceFAQs(slug:string){return faqs.filter(f=>f.category===(slug.startsWith('medical')?'medical':slug));}
