'use client';
import {useState,useRef,type FormEvent} from 'react';
import type {Language} from './content';
import {ui,T,type Text,services} from './international-data';
import {countries} from './international-countries';
import {Button} from '@/components/ui/button';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {CheckCircle2,Upload,Search} from 'lucide-react';
interface Field{name:string;label:Text;type?:string;options?:{value:string,label:Text}[];required?:boolean;min?:number;max?:number;}
const option=(value:string,label:Text)=>({value,label});
const education:Field[]=[{name:'age',label:T('سن','Age','Yaş'),type:'number',min:0,max:120,required:true},{name:'qualification',label:T('آخرین مدرک','Highest qualification','Son diploma'),required:true},{name:'gpa',label:T('معدل و مقیاس آن','Grade / GPA and scale','Not / ortalama ve ölçek'),required:true},{name:'field',label:T('رشتهٔ موردنظر','Intended field','İstenen bölüm'),required:true},{name:'languageLevel',label:T('سطح زبان','Language level','Dil düzeyi'),required:true},{name:'budget',label:T('بودجهٔ سالانه و ارز','Annual budget and currency','Yıllık bütçe ve para birimi'),required:true}];
const currencies=['USD','EUR','GBP','TRY','CNY','RUB','AED','CHF'];
const financial:Field[]=[{name:'sourceCurrency',label:T('ارز مبدأ','Source currency','Kaynak para birimi'),options:currencies.map(s=>option(s,T(s,s,s))),required:true},{name:'targetCurrency',label:T('ارز مقصد','Target currency','Hedef para birimi'),options:currencies.map(s=>option(s,T(s,s,s))),required:true},{name:'amount',label:T('مبلغ','Amount','Tutar'),type:'number',min:.01,max:100000000,required:true},{name:'sourceCountry',label:T('کشور مبدأ پرداخت','Sending country','Gönderen ülke'),required:true},{name:'transferType',label:T('نوع پرداخت','Payment purpose','Ödeme amacı'),options:[option('tuition',T('شهریه','Tuition','Okul ücreti')),option('hotel',ui.hotel),option('medical',ui.medical),option('transfer',T('حواله یا تبدیل','Transfer or conversion','Transfer veya dönüşüm'))],required:true}];
const hotel:Field[]=[{name:'checkIn',label:T('تاریخ ورود','Check-in','Giriş tarihi'),type:'date',required:true},{name:'checkOut',label:T('تاریخ خروج','Check-out','Çıkış tarihi'),type:'date',required:true},{name:'travelers',label:T('تعداد مسافران','Travelers','Yolcu sayısı'),type:'number',min:1,max:100,required:true},{name:'rooms',label:T('تعداد اتاق','Rooms','Oda sayısı'),type:'number',min:1,max:50,required:true},{name:'budget',label:T('بودجه و ارز','Budget and currency','Bütçe ve para birimi'),required:true}];
const medical:Field[]=[{name:'specialty',label:T('تخصص موردنیاز','Requested specialty','İstenen uzmanlık'),required:true,options:[T('دندان‌پزشکی','Dentistry','Diş hekimliği'),T('زیبایی','Aesthetics','Estetik'),T('چشم','Ophthalmology','Göz'),T('ارتوپدی','Orthopaedics','Ortopedi'),T('قلب','Cardiology','Kardiyoloji'),T('زنان','Gynaecology','Kadın sağlığı'),T('ناباروری','Fertility','Üreme sağlığı'),T('چکاپ','Health check','Check-up')].map((s,i)=>option(String(i),s))},{name:'age',label:T('سن','Age','Yaş'),type:'number',min:0,max:120},{name:'travelDate',label:T('زمان پیشنهادی سفر','Preferred travel date','Tercih edilen seyahat tarihi'),type:'date'},{name:'companion',label:T('آیا همراه دارید؟','Traveling with a companion?','Refakatçi var mı?'),options:[option('yes',T('بله','Yes','Evet')),option('no',T('خیر','No','Hayır'))]}];
const insurance:Field[]=[{name:'insuranceType',label:T('نوع بیمه','Insurance type','Sigorta türü'),required:true,options:[option('travel',T('مسافرتی','Travel','Seyahat')),option('student',T('دانشجویی','Student','Öğrenci')),option('health',T('درمانی','Health','Sağlık')),option('residency',ui.residency),option('family',T('خانواده','Family','Aile'))]},{name:'startDate',label:T('تاریخ شروع','Start date','Başlangıç tarihi'),type:'date',required:true},{name:'duration',label:T('مدت پوشش','Coverage duration','Teminat süresi'),required:true},{name:'age',label:T('سن متقاضی','Applicant age','Başvuru yaşı'),type:'number',min:0,max:120,required:true}];
const residency:Field[]=[{name:'nationality',label:T('تابعیت','Nationality','Vatandaşlık'),required:true},{name:'age',label:T('سن','Age','Yaş'),type:'number',min:0,max:120,required:true},{name:'route',label:T('مسیر موردنظر','Intended route','İstenen yol'),required:true,options:[option('study',ui.study),option('work',T('کاری','Employment','Çalışma')),option('family',T('خانوادگی','Family','Aile')),option('investment',T('سرمایه‌گذاری قانونی','Lawful investment','Yasal yatırım')),option('evaluate',T('نیاز به ارزیابی','Need assessment','Değerlendirme gerekli'))]},{name:'qualification',label:T('تحصیلات','Education','Eğitim')},{name:'workHistory',label:T('سابقهٔ کار','Work experience','İş deneyimi')},{name:'family',label:T('وضعیت خانواده و همراهان','Family and dependants','Aile ve bağımlılar')},{name:'languageLevel',label:T('سطح زبان','Language level','Dil düzeyi')},{name:'budget',label:T('بودجه و ارز','Budget and currency','Bütçe ve para birimi'),required:true}];
function fieldsFor(service:string){if(service==='study-abroad')return education;if(service==='exchange')return financial;if(service==='crypto-exchange')return [{name:'asset',label:T('دارایی — نمونه‌ها','Asset — examples','Varlık — örnekler'),required:true,options:['USDT','Bitcoin','Ethereum'].map(s=>option(s,T(s,s,s)))},{name:'network',label:T('شبکه — بررسی سازگاری الزامی است','Network — compatibility must be verified','Ağ — uyumluluk doğrulanmalı'),required:true,options:['TRC20','ERC20','BEP20','Bitcoin'].map(s=>option(s,T(s,s,s)))},{name:'amount',label:T('مقدار دارایی','Asset amount','Varlık tutarı'),required:true,type:'number',min:.000001,max:100000000},{name:'operation',label:T('نوع درخواست','Inquiry type','Talep türü'),required:true,options:[option('buy',T('خرید','Buy','Alım')),option('sell',T('فروش','Sell','Satım')),option('transfer',T('انتقال','Transfer','Transfer'))]}] as Field[];if(service==='hotel-reservation')return hotel;if(service.startsWith('medical'))return medical;if(service==='insurance')return insurance;if(service==='residency')return residency;return[];}
export function RequestForm({lang,initialService='general',initialDestination='',quick=false}:{lang:Language;initialService?:string;initialDestination?:string;quick?:boolean}){
 const [service,setService]=useState(initialService),[status,setStatus]=useState<'idle'|'sending'|'saved'|'error'>('idle'),[files,setFiles]=useState<File[]>([]),[uploadError,setUploadError]=useState(''),[result,setResult]=useState<{code:string,key:string}|null>(null),[copied,setCopied]=useState(false);const creds=useRef<{id:string,secret:string}|null>(null);const fileInput=useRef<HTMLInputElement>(null);
 const allServices=[...services.map(s=>({slug:s.slug,title:s.title})),{slug:'medical/dentistry',title:T('دندان‌پزشکی','Dentistry','Diş hekimliği')},{slug:'medical/treatment',title:T('هماهنگی درمان','Treatment coordination','Tedavi koordinasyonu')},{slug:'general',title:T('مشاورهٔ عمومی','General consultation','Genel danışmanlık')}];const medicalPage=service.startsWith('medical');const extra=quick?[]:fieldsFor(service);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(status==='sending'||uploadError)return;const form=e.currentTarget;if(!form.reportValidity())return;const data=new FormData(form);const details=Object.fromEntries(extra.map(f=>[f.name,String(data.get(f.name)||'')]));if(service==='hotel-reservation'&&!quick&&details.checkOut<=details.checkIn){setUploadError(T('تاریخ خروج باید پس از ورود باشد.','Check-out must follow check-in.','Çıkış tarihi girişten sonra olmalı.')[lang]);return;}setStatus('sending');if(!creds.current){const bytes=crypto.getRandomValues(new Uint8Array(32));creds.current={id:crypto.randomUUID(),secret:Array.from(bytes,v=>v.toString(16).padStart(2,'0')).join('')};}
 const payload={...creds.current,name:String(data.get('name')||''),email:String(data.get('email')||''),phone:String(data.get('phone')||''),country:String(data.get('country')||''),service,destination:String(data.get('destination')||''),method:String(data.get('method')||'email'),time:String(data.get('time')||''),message:String(data.get('message')||''),details,consent:data.get('consent')==='on',medicalConsent:data.get('medicalConsent')==='on',language:lang,website:String(data.get('website')||''),formType:quick?'quick':'full'};
 const body=new FormData();body.set('payload',JSON.stringify(payload));if(medicalPage&&!quick)files.forEach(f=>body.append('files',f));try{const r=await fetch('/api/requests',{method:'POST',body});if(!r.ok)throw Error();const response=await r.json() as {code:string};setResult({code:response.code,key:creds.current.secret});setStatus('saved');}catch{setStatus('error');}}
 function pickFiles(list:FileList|null){const arr=Array.from(list||[]);if(arr.length>3||arr.some(f=>f.size>5*1024*1024||!['application/pdf','image/png','image/jpeg'].includes(f.type))){setUploadError(ui.uploadNote[lang]);setFiles([]);if(fileInput.current)fileInput.current.value='';}else{setFiles(arr);setUploadError('');}}
 const input=(name:string,label:Text,type='text',required=false,defaultValue='',extraProps:Record<string,unknown>={})=><label key={name}>{label[lang]}{required?' *':''}<input name={name} type={type} required={required} defaultValue={defaultValue} maxLength={type==='text'?150:undefined} minLength={name==='name'?2:name==='phone'?5:undefined} autoComplete={name==='name'?'name':name==='email'?'email':name==='phone'?'tel':undefined} dir={['email','tel','number','date'].includes(type)?'ltr':undefined} {...extraProps}/></label>;
 if(result)return <div className="intl-form-success" role="status"><CheckCircle2 size={34}/><h3>{ui.saved[lang]}</h3><label>{ui.code[lang]}<code>{result.code}</code></label><label>{ui.key[lang]}<code>{result.key}</code></label><Button className="intl-button" onClick={async()=>{try{await navigator.clipboard.writeText(`${result.code}\n${result.key}`);setCopied(true);}catch{setCopied(false);}}}>{copied?ui.copied[lang]:ui.copy[lang]}</Button><a href={`/${lang}/track-request`}>{ui.track[lang]}</a></div>;
 return <form className={'intl-request-form '+(quick?'quick-form':'')} onSubmit={submit} onChange={e=>{if(status==='error')setStatus('idle');creds.current=null;if(uploadError&&('type' in e.target ? e.target.type : '')!=='file')setUploadError('');}}>{input('name',ui.name,'text',true)}{input('phone',ui.phone,'tel',true)}{input('email',ui.email,'email',true)}{!quick&&input('country',ui.country)}<label>{ui.service[lang]} *<Select value={service} onValueChange={v=>{setService(v);creds.current=null;setFiles([]);}} dir={lang==='fa'?'rtl':'ltr'}><SelectTrigger className="intl-select" aria-label={ui.service[lang]}><SelectValue/></SelectTrigger><SelectContent className="intl-select-menu">{allServices.map(s=><SelectItem key={s.slug} value={s.slug}>{s.title[lang]}</SelectItem>)}</SelectContent></Select></label>{input('destination',ui.destination,'text',!quick,initialDestination)}{!quick&&<><label>{ui.method[lang]}<Select name="method" defaultValue="email" dir={lang==='fa'?'rtl':'ltr'}><SelectTrigger className="intl-select"><SelectValue/></SelectTrigger><SelectContent className="intl-select-menu">{['email','phone','whatsapp'].map(s=><SelectItem key={s} value={s}>{s==='email'?ui.email[lang]:s==='phone'?ui.phone[lang]:'WhatsApp'}</SelectItem>)}</SelectContent></Select></label>{input('time',ui.time)}</>}{extra.map(f=>f.options?<label key={f.name}>{f.label[lang]}{f.required?' *':''}<Select name={f.name} required={f.required} dir={lang==='fa'?'rtl':'ltr'}><SelectTrigger className="intl-select" aria-label={f.label[lang]}><SelectValue placeholder={ui.choose[lang]}/></SelectTrigger><SelectContent className="intl-select-menu">{f.options.map(o=><SelectItem key={o.value} value={o.value}>{o.label[lang]}</SelectItem>)}</SelectContent></Select></label>:input(f.name,f.label,f.type||'text',f.required,'',{min:f.min,max:f.max,step:f.type==='number'?'any':undefined}))}
 {!quick&&<label className="full">{ui.message[lang]}<textarea name="message" rows={4} maxLength={4000}/></label>}
 {medicalPage&&!quick&&<><label className="full intl-file-label"><Upload size={18}/>{ui.upload[lang]}<input ref={fileInput} type="file" multiple accept="application/pdf,image/jpeg,image/png" onChange={e=>pickFiles(e.target.files)}/><small>{ui.uploadNote[lang]}</small>{files.length>0&&<small>{files.map(f=>f.name).join(' · ')}</small>}</label><label className="full consent-row"><Checkbox name="medicalConsent" required={files.length>0} className="intl-checkbox"/>{ui.medicalConsent[lang]}</label></>}
 <label className="full consent-row"><Checkbox name="consent" required className="intl-checkbox"/>{ui.consent[lang]} <a href={`/${lang}/privacy`}>{ui.privacy[lang]}</a></label><input name="website" className="intl-honeypot" tabIndex={-1} aria-hidden="true" autoComplete="off"/>{uploadError&&<p className="full intl-form-error" role="alert">{uploadError}</p>}{status==='error'&&<p className="full intl-form-error" role="alert">{ui.error[lang]}</p>}<div className="full"><Button type="submit" className="intl-button" disabled={status==='sending'}>{status==='sending'?ui.sending[lang]:ui.send[lang]}</Button></div></form>;
}
export function TrackRequest({lang}:{lang:Language}){const [state,setState]=useState('idle'),[result,setResult]=useState<{code:string,service:string,status:string,created_at:number}|null>(null);async function track(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);setState('loading');try{const r=await fetch('/api/requests/track',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:String(data.get('code')).trim(),key:String(data.get('key')).trim()})});if(!r.ok){setState(r.status===404?'missing':'error');setResult(null);return;}const d=await r.json() as {request:{code:string,service:string,status:string,created_at:number}};setResult(d.request);setState('done');}catch{setState('error');}}return <div className="intl-tracking"><form className="intl-request-form" onSubmit={track}><label>{ui.code[lang]}<input name="code" required placeholder="CG-…" dir="ltr"/></label><label>{ui.key[lang]}<input name="key" type="password" required autoComplete="off" dir="ltr"/></label><Button className="intl-button" type="submit" disabled={state==='loading'}><Search size={16}/>{state==='loading'?ui.sending[lang]:ui.track[lang]}</Button></form>{state==='missing'&&<p role="alert">{ui.notFound[lang]}</p>}{state==='error'&&<p role="alert">{ui.error[lang]}</p>}{result&&<div className="intl-track-result" role="status"><CheckCircle2/><h3>{ui.received[lang]}</h3><p>{result.code}</p><span>{new Date(result.created_at).toLocaleDateString(lang==='fa'?'fa-IR':lang==='tr'?'tr-TR':'en-GB')}</span></div>}</div>;}
