'use client';
import {useEffect,useRef} from 'react';
export default function InternationalNetwork({mode='globe'}:{mode?:'globe'|'flow'|'medical'|'hotel'}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const c=ref.current!;const ctx=c.getContext('2d');if(!ctx)return;let raf=0,visible=false,t=0,mouse=0,stopped=false;const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;const points=Array.from({length:1800},(_,i)=>{const y=1-2*(i+.5)/1800;return{y,r:Math.sqrt(1-y*y),a:i*2.399963};});
 const draw=()=>{if(stopped)return;const size=c.clientWidth,dpr=Math.min(devicePixelRatio,1.5);if(c.width!==Math.round(size*dpr)){c.width=Math.round(size*dpr);c.height=Math.round(size*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,size,size);const r=size*.34;const rotation=t*.003+mouse;
 const project=(a:number,y:number,rr:number)=>{const x=Math.cos(a+rotation)*rr,z=Math.sin(a+rotation)*rr;return{x:size/2+x*r,y:size/2+(y*.94+z*.25)*r,z};};
 if(mode==='flow'){for(let k=0;k<6;k++){ctx.beginPath();for(let i=0;i<=100;i++){const x=i/100*size,y=size/2+Math.sin(i*.04+k*.35)*size*.13+(k-3)*13;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.strokeStyle=`rgba(255,255,255,${.07+k*.025})`;ctx.stroke();for(let j=0;j<4;j++){const x=((t*.8+j*size/4+k*35)%size);const y=size/2+Math.sin(x/size*4+k*.35)*size*.13+(k-3)*13;ctx.fillStyle='#bbb';ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill();}}}
 else{for(const p of points){const v=project(p.a,p.y,p.r);ctx.globalAlpha=.12+(v.z+1)*.3;ctx.fillStyle='#e8e8e8';ctx.beginPath();ctx.arc(v.x,v.y,.6+(v.z+1)*.5,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
 for(let k=0;k<3;k++){ctx.beginPath();ctx.ellipse(size/2,size/2,r*1.24,r*.38,k*1.1,0,Math.PI*2);ctx.strokeStyle='#ffffff1c';ctx.stroke();}
 for(let k=0;k<7;k++){const v=project(k*.86,.35*Math.sin(k*1.5),.92);if(v.z>-.3){ctx.beginPath();ctx.arc(v.x,v.y,4,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.beginPath();ctx.arc(v.x,v.y,9,0,Math.PI*2);ctx.strokeStyle='#ffffff55';ctx.stroke();}}}
 t++;if(visible&&!document.hidden&&!reduced)raf=requestAnimationFrame(draw);};const obs=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible){cancelAnimationFrame(raf);draw();}else cancelAnimationFrame(raf);});obs.observe(c);const pointer=(e:PointerEvent)=>{mouse=(e.clientX/innerWidth-.5)*.25;};const resume=()=>{if(visible&&!document.hidden){cancelAnimationFrame(raf);draw();}};window.addEventListener('pointermove',pointer,{passive:true});document.addEventListener('visibilitychange',resume);draw();return()=>{stopped=true;cancelAnimationFrame(raf);obs.disconnect();window.removeEventListener('pointermove',pointer);document.removeEventListener('visibilitychange',resume);};},[mode]);
 return <div className={`intl-network ${mode}`} aria-hidden="true"><canvas ref={ref}/><span className="network-coord">CG / INTERNATIONAL NETWORK</span><span className="network-tag one">EDUCATION</span><span className="network-tag two">TRAVEL</span><span className="network-tag three">CONNECTED SERVICES</span></div>;
}
