'use client';
import {leadWhatsAppLink} from '@/lib/whatsapp-link';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { content, type Language } from './content';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetTrigger, SheetContent, SheetTitle, SheetDescription, SheetClose } from '@/components/ui/sheet';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Phone, AudioLines, Globe, Smartphone, CalendarDays, Check, Menu, Cpu, Layers, MessageSquare, CircleCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';

function Core() {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current!; const ctx = canvas.getContext('2d')!;
    let frame = 0, running = true, visible = true, raf = 0, pointer = 0; const reduced = matchMedia('(prefers-reduced-motion: reduce)').matches;
    const onMove=(e:PointerEvent)=>{pointer=(e.clientX/innerWidth-.5)*.3;};window.addEventListener('pointermove',onMove,{passive:true});
    const draw = () => {
      const size = canvas.clientWidth; const dpr = Math.min(devicePixelRatio, 2);
      if (canvas.width !== size*dpr) { canvas.width=size*dpr; canvas.height=size*dpr; }
      ctx.setTransform(dpr,0,0,dpr,0,0); ctx.clearRect(0,0,size,size);
      const t=frame*.003+pointer; const r=size*.33;
      for(let i=0;i<2700;i++) {
        const y=1-2*(i+.5)/2700, rr=Math.sqrt(1-y*y), a=i*2.399963+t;
        let x=Math.cos(a)*rr, z=Math.sin(a)*rr;
        const yy=y*Math.cos(.35)+z*Math.sin(.35); z=z*Math.cos(.35)-y*Math.sin(.35);
        const scale=1+z*.18; const alpha=.13+(z+1)*.35;
        ctx.fillStyle=`rgba(235,239,241,${alpha})`; ctx.beginPath(); ctx.arc(size/2+x*r*scale,size/2+yy*r*scale,.6+(z+1)*.45,0,Math.PI*2);ctx.fill();
      }
      frame++; if(running && visible && !document.hidden && !reduced) raf=requestAnimationFrame(draw);
    };const observer=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible){cancelAnimationFrame(raf);draw();}});observer.observe(canvas);
    const onVisibility=()=>{if(!document.hidden&&visible){cancelAnimationFrame(raf);draw();}};document.addEventListener('visibilitychange',onVisibility);
    draw(); return()=>{running=false;cancelAnimationFrame(raf);observer.disconnect();window.removeEventListener('pointermove',onMove);document.removeEventListener('visibilitychange',onVisibility);};
  },[]);
  return <div className="core-wrap"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><canvas ref={ref} aria-label="Animated particle visualization of an AI core"/><span className="core-label label-voice">VOICE</span><span className="core-label label-auto">AUTOMATION</span><span className="core-label label-data">INTELLIGENCE</span><div className="core-coordinate">CG — INTELLIGENCE ENGINE / 01</div></div>;
}

type Copy = typeof content.en;
const ids=['home','solutions','reception','call-center','web','mobile','about','contact'];
const serviceIds=['reception','call-center','web','mobile'];
const icons=[Phone,AudioLines,Globe,Smartphone];
function CallDemo({t}:{t:Copy}){
 const ref=useRef<HTMLDivElement>(null);const [step,setStep]=useState(0);const [active,setActive]=useState(false);
 useEffect(()=>{const el=ref.current!;const observer=new IntersectionObserver(([e])=>{if(e.isIntersecting){setActive(true);observer.disconnect();}},{threshold:.3});observer.observe(el);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!active)return;setStep(0);const timers=[1,2,3,4,5].map((s)=>setTimeout(()=>setStep(s),s*1700));return()=>timers.forEach(clearTimeout);},[active]);
 function replay(){setActive(false);setStep(0);setTimeout(()=>setActive(true),50);}
 return <div className="call-demo" ref={ref}><div className="demo-title"><span className="eyebrow">{t.live}</span><AudioLines size={18}/></div><div className="call-heading"><div className="phone-icon"><Phone size={20}/></div><div><strong>{t.incoming}</strong><span>{t.agent}</span></div><span className="call-timer">00:{String(Math.min(step*5,24)).padStart(2,'0')}</span></div><div className={'waveform '+(step<5&&active?'playing':'')}>{Array.from({length:48},(_,i)=><i key={i} style={{height:`${Math.round(10+Math.sin(i*.65)**2*39)}px`,animationDelay:`${(i*-.09).toFixed(2)}s`}}/>)}</div><div className="transcript" aria-live="polite">{t.transcript.map((line,i)=><div className={'chat '+(i%2?'agent-chat':'customer-chat')+(step>i?' visible':'')} key={i}><span>{i%2?t.agent:t.customer}</span><p>{line}</p></div>)}</div><div className={'confirmation '+(step>=5?'confirmed':'')}><CalendarDays size={22}/><div><strong>{step>=5?t.confirmed:t.processing}</strong><span>{step>=5?t.appointment:'CRM + Calendar'}</span></div>{step>=5&&<CircleCheck size={20}/>}</div><div className="demo-footer"><span>{t.simulated}</span><button onClick={replay}>{active?t.replay:t.play}</button></div></div>;
}
function Contact({t,lang}:{t:Copy,lang:Language}){
 const [interest,setInterest]=useState('');const [industry,setIndustry]=useState('');const [state,setState]=useState<'idle'|'sending'|'success'|'error'>('idle');const requestId=useRef('');const [whatsappLink,setWhatsappLink]=useState('');
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(state==='sending')return;const form=e.currentTarget;if(!form.reportValidity())return;setState('sending');const data=Object.fromEntries(new FormData(form));if(!requestId.current)requestId.current=crypto.randomUUID();try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,id:requestId.current,interest,industry,language:lang})});if(!r.ok)throw Error();setWhatsappLink(leadWhatsAppLink({code:'CG-'+requestId.current.replace(/-/g,'').slice(0,16).toUpperCase(),name:String(data.name||''),phone:String(data.phone||''),email:String(data.email||''),service:interest}));setState('success');form.reset();setInterest('');setIndustry('');requestId.current='';}catch{setState('error');}}
 return <form className="contact-form" onSubmit={submit}>{['name','company','email','phone','country'].map((name,i)=><label key={name}>{t.fields[i]}{i===0||i===2?' *':''}<input name={name} required={i===0||i===2} type={i===2?'email':i===3?'tel':'text'} minLength={i===0?2:undefined} maxLength={i===2?254:i===3?50:150} placeholder={t.placeholders[i]} autoComplete={['name','organization','email','tel','country-name'][i]} dir={i===2||i===3?'ltr':undefined} onChange={()=>{requestId.current='';}}/></label>)}<label>{t.fields[5]}<Select value={industry} onValueChange={setIndustry} dir={lang==='fa'?'rtl':'ltr'}><SelectTrigger className="form-select" aria-label={t.fields[5]}><SelectValue placeholder={t.placeholders[5]}/></SelectTrigger><SelectContent>{t.industries.map((s,i)=><SelectItem key={i} value={s}>{s}</SelectItem>)}</SelectContent></Select></label><label className="full">{t.fields[6]} *<Select required value={interest} onValueChange={setInterest} dir={lang==='fa'?'rtl':'ltr'}><SelectTrigger className="form-select" aria-label={t.fields[6]}><SelectValue placeholder={t.placeholders[6]}/></SelectTrigger><SelectContent>{[...t.services,t.custom].map((s,i)=><SelectItem key={i} value={['reception','calls','web','mobile','custom'][i]}>{s}</SelectItem>)}</SelectContent></Select></label><label className="full">{t.fields[7]} *<textarea required minLength={10} maxLength={5000} name="message" placeholder={t.placeholders[7]} rows={4} onChange={()=>{requestId.current='';}}/></label><input name="website" className="honeypot" tabIndex={-1} aria-hidden="true" autoComplete="off"/><div className="form-bottom full"><Button className="primary" type="submit" disabled={state==='sending'}>{state==='sending'?t.sending:t.send}</Button><span>{t.privacy}</span></div>{(state==='success'||state==='error')&&<p className="form-feedback full" role="status">{state==='success'?t.success:t.error}</p>}{state==='success'&&whatsappLink&&<div className="full"><a className="intl-whatsapp-action" href={whatsappLink} target="_blank" rel="noopener noreferrer">{lang==='fa'?'ادامه در واتس‌اپ':lang==='tr'?'WhatsApp ile devam et':'Continue on WhatsApp'}</a><p>{lang==='fa'?'پیام آماده را باز کنید و در واتس‌اپ ارسال را بزنید.':lang==='tr'?'Hazır mesajı açın ve WhatsApp içinde Gönder’e dokunun.':'Open the prepared message and tap Send in WhatsApp.'}</p></div>}</form>;
}
function Kicker({t,index}:{t:Copy,index:number}){return <div className="section-top"><span className="eyebrow">{String(index+1).padStart(2,'0')} / {t.sections[index]}</span><span className="section-line"/></div>;}
function Features({items}:{items:string[]}){return <ul className="feature-list">{items.map(s=><li key={s}><Check size={14}/>{s}</li>)}</ul>;}
export default function CreatorSite({lang}:{lang:Language}) {
 const t=content[lang];const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='fa'?'rtl':'ltr';const onScroll=()=>setScrolled(scrollY>25);window.addEventListener('scroll',onScroll,{passive:true});onScroll();const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');obs.unobserve(e.target);}}),{threshold:.07});document.querySelectorAll('.reveal').forEach(el=>obs.observe(el));return()=>{window.removeEventListener('scroll',onScroll);obs.disconnect();};},[lang]);
 const schema={'@context':'https://schema.org','@graph':[{'@type':'Organization','name':'Creator Group','url':'https://creatorgroup.io','description':t.aboutDesc},{'@type':'Service','provider':{'@type':'Organization','name':'Creator Group'},'name':t.services.join(', '),'description':t.intro}]};
 return <main className={lang==='fa'?'persian':''} dir={lang==='fa'?'rtl':'ltr'}>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,'\\u003c')}}/>
 <a className="skip-link" href="#solutions">{t.explore}</a>
 <header className={scrolled?'scrolled':''}><a className="brand" href={`/${lang}`} aria-label="Creator Group"><img className="creator-logo" src="/brand/creator-logo.webp" alt="Creator logo"/><span>CREATOR<br/>GROUP</span></a><nav aria-label={t.menu}><a href={`/${lang}`}>{lang==='fa'?'سایت اصلی':lang==='tr'?'Ana site':'Main website'}</a><a href="#solutions">{t.nav[1]}</a><a href="#web">{lang==='en'?'Digital Products':lang==='tr'?'Dijital Ürünler':'محصولات دیجیتال'}</a><a href="#about">{t.nav[6]}</a></nav><div className="nav-end"><div className="languages" aria-label="Language">{(['en','tr','fa'] as Language[]).map(l=><a href={`/${l}/services`} key={l} lang={l} hrefLang={l} className={l===lang?'selected':''} aria-current={l===lang?'page':undefined}>{l.toUpperCase()}</a>)}</div><Button asChild className="primary small"><a href="#contact">{t.demo}</a></Button><Sheet><SheetTrigger asChild><Button className="menu-button" variant="ghost" aria-label={t.menu}><Menu/></Button></SheetTrigger><SheetContent side={lang==='fa'?'left':'right'} className="mobile-sheet"><SheetTitle>{t.menu}</SheetTitle><SheetDescription>CREATOR GROUP</SheetDescription>{t.nav.map((s,i)=><SheetClose asChild key={s}><a href={`#${ids[i]}`} className="mobile-nav-link">{s}</a></SheetClose>)}</SheetContent></Sheet></div></header>
 <section className="hero" id="home"><div className="hero-copy"><div className="eyebrow"><span className="status-dot"/>{t.eyebrow}</div><h1>{t.hero[0]}<br/>{t.hero[1]}<br/><span>{t.hero[2]}</span></h1><p>{t.intro}</p><div className="hero-actions"><Button asChild className="primary"><a href="#contact">{t.demo}</a></Button><a className="text-link" href="#solutions">{t.explore}<span>↗</span></a></div></div><Core/><div className="hero-bottom"><span>{t.system}<i/>{t.online}</span><span>{t.scroll}<b>↓</b></span><span>{t.next}</span></div></section>
 <section id="solutions" className="section reveal"><Kicker t={t} index={0}/><div className="headline-row"><h2>{t.expertise[0]}<br/><span>{t.expertise[1]}</span></h2><p>{t.smarter}</p></div><div className="service-grid">{t.services.map((s,i)=>{const Icon=icons[i];return <a href={`#${serviceIds[i]}`} className="service-card" key={s}><span className="muted">0{i+1}</span><div className="service-symbol"><Icon size={48} strokeWidth={.8}/></div><h3>{s}</h3><p>{t.serviceDesc[i]}</p><span className="service-arrow">↗</span></a>;})}</div></section>
 <section id="reception" className="section split reveal"><div><Kicker t={t} index={1}/><h2>{t.reception[0]}<br/><span>{t.reception[1]}</span></h2><p className="section-description">{t.receptionDesc}</p><Features items={t.receptionFeatures}/><a href="#contact" className="underlined">{t.demo}</a></div><CallDemo t={t}/></section>
 <section id="call-center" className="section reveal"><Kicker t={t} index={2}/><div className="split-heading"><h2>{t.callCenter[0]}<br/><span>{t.callCenter[1]}</span></h2><p>{t.callDesc}</p></div><div className="call-center-board"><div className="signal-visual" aria-hidden="true">{Array.from({length:43},(_,i)=><i key={i} style={{height:`${Math.round(20+Math.sin(i*.2)**2*100)}px`,animationDelay:`${(i*-.12).toFixed(2)}s`}}/>)}</div><div className="capability-grid">{t.callFeatures.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</div>)}</div><div className="language-strip"><Globe size={16}/><span>{t.languages}</span></div><p className="capability-note">{t.capabilities}</p></div></section>
 <section id="appointments" className="section reveal"><Kicker t={t} index={3}/><div className="split-heading"><h2>{t.calendar[0]}<br/><span>{t.calendar[1]}</span></h2><p>{t.calendarDesc}</p></div><div className="workflow">{t.flow.map((s,i)=><div className="flow-step" key={s}><span className="flow-num">{String(i+1).padStart(2,'0')}</span>{i===0?<Phone/>:i===3?<CalendarDays/>:i===5?<CircleCheck/>:<Cpu/>}<h3>{s}</h3></div>)}</div><div className="integration-row">{t.integrations.map(s=><span key={s}>{s}</span>)}</div></section>
 <section id="industries" className="section reveal"><Kicker t={t} index={4}/><Tabs defaultValue="0" dir={lang==='fa'?'rtl':'ltr'} className="industry-tabs"><TabsList className="industry-list" variant="line">{t.industries.map((s,i)=><TabsTrigger key={i} value={String(i)}>{s}</TabsTrigger>)}</TabsList>{t.industries.map((s,i)=><TabsContent value={String(i)} key={i}><div className="industry-content"><div><span className="eyebrow">{s}</span><h2>{t.industryTitles[i]}</h2><p>{t.industryDesc[i]}</p><a href="#contact" className="underlined">{t.demo}</a></div><div className="industry-graphic"><span className="industry-number">0{i+1}</span><span>{s}</span><div className="industry-ring"><Cpu size={48} strokeWidth={1}/></div></div></div></TabsContent>)}</Tabs></section>
 <section id="web" className="section split reveal"><div><Kicker t={t} index={5}/><h2>{t.web[0]}<br/><span>{t.web[1]}</span></h2><p className="section-description">{t.webDesc}</p><Features items={t.webFeatures}/><a href="#contact" className="underlined">{t.project}</a></div><div className="browser-preview"><div className="browser-top"><i/><i/><i/><span>workspace.creatorgroup.io</span></div><div className="browser-app"><aside><span className="mini-logo">CG</span><Layers/><CalendarDays/><MessageSquare/></aside><div className="browser-content"><span className="eyebrow">{t.interface[4]}</span><h3>{t.interface[0]}</h3><div className="preview-stats"><div><CalendarDays/><span>{t.interface[1]}</span></div><div><AudioLines/><span>{t.interface[2]}</span></div></div><div className="chart" aria-hidden="true">{[25,37,33,48,44,60,55,70,62,87,78,95].map((v,i)=><i style={{height:`${v}%`}} key={i}/>)}</div><h4>{t.interface[3]}</h4>{['09:00','11:30','14:30'].map((v,i)=><div className="schedule-row" key={v}><span>{v}</span><div/><Check size={14}/></div>)}</div></div></div></section>
 <section id="mobile" className="section split reverse reveal"><div className="phone-preview"><div className="app-phone"><div className="phone-notch"/><div className="phone-screen"><div className="phone-app-top"><span className="mini-logo">CG</span><Menu size={16}/></div><span className="eyebrow">{t.interface[9]}</span><h3>{t.interface[5]}</h3><div className="booking-card"><CalendarDays size={36} strokeWidth={1}/><h3>{t.interface[6]}</h3><span>{t.confirmed}</span></div><div className="phone-row">{t.interface[7]}<Check size={16}/></div><div className="phone-row">{t.interface[8]}<CalendarDays size={16}/></div><div className="phone-tabbar"><Globe/><CalendarDays/><MessageSquare/></div></div></div><span className="phone-caption">iOS / ANDROID / FLUTTER</span></div><div><span className="eyebrow">{t.services[3]}</span><h2>{t.mobile[0]}<br/><span>{t.mobile[1]}</span></h2><p className="section-description">{t.mobileDesc}</p><Features items={t.mobileFeatures}/><a href="#contact" className="underlined">{t.project}</a></div></section>
 <section id="ecosystem" className="section ecosystem-section reveal"><Kicker t={t} index={6}/><h2>{t.ecosystem[0]}<br/><span>{t.ecosystem[1]}</span></h2><p className="section-description">{t.ecoDesc}</p><div className="ecosystem"><div className="eco-node customer-node">{t.customers}</div><div className="eco-connector"/><div className="eco-row">{t.services.map((s,i)=>{const Icon=icons[i];return <div className="eco-node" key={s}><Icon size={20}/>{s}</div>;})}</div><div className="eco-connector"/><div className="eco-row integrations">{['CRM','Calendar','WhatsApp','Email',t.database].map(s=><div className="eco-node" key={s}>{s}</div>)}</div><div className="eco-connector"/><div className="eco-node business-node"><span className="status-dot"/>{t.business}</div></div></section>
 <section id="process" className="section reveal"><Kicker t={t} index={7}/><h2>{t.how[0]}<br/><span>{t.how[1]}</span></h2><div className="process-grid">{t.steps.map((s,i)=><div className="process-step" key={s}><span>0{i+1}</span><h3>{s}</h3><p>{t.stepDesc[i]}</p></div>)}</div><div className="metrics">{['24/7','3','100%','AI'].map((s,i)=><div key={s}><strong>{s}</strong><span>{t.metrics[i]}</span></div>)}</div></section>
 <section id="technology" className="section reveal"><Kicker t={t} index={8}/><div className="split-heading"><h2>{t.tech[0]}<br/><span>{t.tech[1]}</span></h2><p>{t.techDesc}</p></div><div className="tech-network">{t.technologies.map((s,i)=><div key={s}><span className="tech-dot"/><span>{s}</span><span className="muted">0{i+1}</span></div>)}</div></section>
 <section className="section split why-section reveal"><div><Kicker t={t} index={9}/><h2>{t.why[0]}<br/><span>{t.why[1]}</span></h2><p className="section-description">{t.whyDesc}</p></div><div className="advantages">{t.advantages.map((s,i)=><div key={s}><span className="muted">0{i+1}</span><h3>{s}</h3><Check size={18}/></div>)}</div></section>
 <section id="case-studies" className="section reveal"><Kicker t={t} index={10}/><h2>{t.cases[0]}<br/><span>{t.cases[1]}</span></h2><p className="case-notice">{t.caseNotice}</p><div className="case-grid">{t.caseTitles.map((s,i)=><article className="case-card" key={s}><span className="eyebrow">{t.industries[[1,0,2][i]]}</span><h3>{s}</h3><h4>{t.problem}</h4><p>{t.caseProblems[i]}</p><h4>{t.solution}</h4><p>{t.caseSolutions[i]}</p><div className="case-tags"><span>Voice AI</span><span>{i===2?'CRM':'Calendar'}</span></div><span className="case-result">{t.results}</span></article>)}</div></section>
 <section id="about" className="section split about-section reveal"><div><Kicker t={t} index={11}/><h2>{t.about[0]}<br/><span>{t.about[1]}</span></h2></div><div className="about-copy"><p>{t.aboutDesc}</p><p className="mission">{t.mission}</p><div className="about-disciplines">AI / AUTOMATION / SOFTWARE / EXPERIENCE</div></div></section>
 <section className="final-cta reveal"><div className="eyebrow">CREATOR GROUP / {t.next}</div><h2>{t.final[0]}<br/>{t.final[1]}<br/><span>{t.final[2]}</span></h2><p>{t.finalDesc}</p><div className="hero-actions"><Button asChild className="primary"><a href="#contact">{t.demo}</a></Button><a href="#contact" className="text-link">{t.project}<span>↗</span></a></div><div className="cta-wave" aria-hidden="true">{Array.from({length:60},(_,i)=><i key={i} style={{height:`${Math.round(20+Math.sin(i*.1)**2*200)}px`}}/>)}</div></section>
 <section id="contact" className="section split reveal"><div><Kicker t={t} index={12}/><h2>{t.contact[0]}<br/><span>{t.contact[1]}</span></h2><p className="section-description">{t.contactDesc}</p><div className="contact-brand">CREATOR GROUP<span>AI / DIGITAL / AUTOMATION</span></div></div><Contact t={t} lang={lang}/></section>
 <footer><div className="footer-top"><a className="brand" href={`/${lang}`}><img className="creator-logo" src="/brand/creator-logo.webp" alt="Creator logo"/><span>CREATOR<br/>GROUP</span></a><div className="footer-links">{t.services.map((s,i)=><a href={`#${serviceIds[i]}`} key={s}>{s}</a>)}<a href="#about">{t.nav[6]}</a><a href="#contact">{t.nav[7]}</a></div><div className="footer-languages"><a href="/en/services">English</a><a href="/tr/services">Türkçe</a><a href="/fa/services">فارسی</a><span>{t.social}</span></div></div><div className="footer-statement">{t.footer}</div><div className="footer-bottom"><span>{t.copyright}</span><span>creatorgroup.io</span><a href="#home">↑</a></div></footer>
 </main>;
}
