import {countrySchema,countryTopics,countryTopicTitles,type Country,type CountryIntelligence,type CountryTopic} from './country-model';
const T=(fa:string,en:string,tr:string)=>({fa,en,tr});
const day='2026-10-03';
type Source={title:string;url:string;type?:CountryIntelligence['source_type'];jurisdiction?:string};
type Seed={code:string;slug:string;name:ReturnType<typeof T>;capital:ReturnType<typeof T>;language:ReturnType<typeof T>[];currency:string;zone:string[];cities:ReturnType<typeof T>[];lat:number;lng:number;overview:ReturnType<typeof T>;source:Source;jurisdiction?:ReturnType<typeof T>};
const sources={
 trStudy:{title:'Council of Higher Education — Study in Türkiye',url:'https://www.studyinturkiye.gov.tr/',type:'official-education' as const},
 trVisa:{title:'Türkiye Ministry of Foreign Affairs — General visa information',url:'https://www.mfa.gov.tr/general-information-about-turkish-visas.en.mfa'},
 trResidence:{title:'Türkiye Presidency of Migration Management — Residence permit types',url:'https://en.goc.gov.tr/residence-permit-types'},
 trWork:{title:'Türkiye Presidency of Migration Management — Foreigners FAQ',url:'https://en.goc.gov.tr/frequently-asked-questions-about-foreigners'},
 trCitizen:{title:'Türkiye NVI — Citizenship Law No. 5901',url:'https://www.nvi.gov.tr/kurumlar/nvi.gov.tr/mevzuat/nufusmevzuat/ingilizce/TURKISH_CITIZENSHIP_LAW_5901.pdf'},
 deStudy:{title:'German Federal Government — Visa for studying',url:'https://www.make-it-in-germany.com/en/visa-residence/types/studying'},
 deWork:{title:'German Federal Government — Study and work',url:'https://www.make-it-in-germany.com/en/study-vocational-training/studies-in-germany/work'},
 deAfter:{title:'German Federal Government — Prospects after graduation',url:'https://www.make-it-in-germany.com/en/study-vocational-training/studies-in-germany/prospects-after'},
 dePR:{title:'German Federal Government — Settlement permit',url:'https://www.make-it-in-germany.com/en/visa-residence/living-permanently/settlement-permit'},
 deCitizen:{title:'Federal Government — Naturalisation prerequisites',url:'https://www.make-it-in-germany.com/en/visa-residence/living-permanently/naturalisation/prerequisites'},
 nlStudy:{title:'IND — University student residence permit',url:'https://ind.nl/en/residence-permits/study/student-residence-permit-for-university-or-higher-professional-education'},
 nlAfter:{title:'IND — Residence permit for orientation year',url:'https://ind.nl/en/residence-permits/work/residence-permit-for-orientation-year'},
 nlPR:{title:'IND — Permanent residence permit',url:'https://ind.nl/en/residence-permits/long-term-eu-residency/permanent-residence-permit'},
 nlPurpose:{title:'IND — Temporary and non-temporary residence purposes',url:'https://ind.nl/en/temporary-and-non-temporary-purposes-of-residence'},
 nlCitizen:{title:'IND — Becoming a Dutch national through naturalisation',url:'https://ind.nl/en/dutch-citizenship/becoming-a-dutch-national-through-naturalisation'},
 cyStudy:{title:'Republic of Cyprus Migration Department — Students',url:'https://www.gov.cy/mip-md/en/documents/students/'},
 cyWork:{title:'Republic of Cyprus — Economic activities by students',url:'https://www.gov.cy/mip-md/en/documents/economic-activities-by-students/'},
 cyPR:{title:'Republic of Cyprus — Long-term resident status',url:'https://www.gov.cy/mip-md/en/documents/acquisition-of-the-status-of-long-term-resident-in-the-republic-2/'},
 cyCitizen:{title:'Republic of Cyprus — Naturalisation, form M127',url:'https://www.gov.cy/moi/en/documents/acquisition-of-cypriot-citizenship-by-naturalization-due-to-years-of-residence-form-m127/'},
 cnVisa:{title:'Chinese Embassy — X1 and X2 study visas',url:'https://pg.china-embassy.gov.cn/lsyw/lszj/fhqz/fhqzjj/202501/t20250108_11528812.html'},
 cnResidence:{title:'Beijing Government — International residence permit instructions',url:'https://english.beijing.gov.cn/mostrequested/residencepermit/international/202405/t20240528_3695884.html',jurisdiction:'Mainland China — Beijing procedures'},
 cnWork:{title:'Beijing Government — Off-campus internship endorsement',url:'https://english.beijing.gov.cn/quickguideservicesleft/202506/t20250604_4105915.html',jurisdiction:'Mainland China — Beijing procedures'},
 ruStudy:{title:'Study in Russia — Education and international student FAQ',url:'https://studyinrussia.ru/en/education?lang=en',type:'official-education' as const},
 ruUniversities:{title:'Study in Russia — University directory',url:'https://studyinrussia.ru/en/university?lang=en',type:'official-education' as const},
 esStudy:{title:'Spain Ministry of Migration — Higher education study authorisation',url:'https://www.inclusion.gob.es/web/migraciones'},
 esWork:{title:'Spain Ministry of Migration — Sheet 4 bis, access to employment',url:'https://www.inclusion.gob.es/es/web/migraciones/w/hoja-4-bis-acceso-al-empleo-de-las-personas-titulares-de-una-autorizacion-de-estancia-de-larga-duracion-por-estudios-movilidad-de-alumnos-servicios-de-voluntariado-o-actividades-formativas'},
 esAfter:{title:'Spain Ministry of Migration — Sheet 20, graduate job search',url:'https://inclusion.gob.es/en/web/migraciones/w/20.-autorizacion-de-residencia-para-busqueda-de-empleo-o-inicio-de-proyecto-empresarial'},
};
function block(seed:Seed,topic:CountryTopic,body:ReturnType<typeof T>,source=seed.source,status:CountryIntelligence['status']='verified'):CountryIntelligence{return {topic,title:countryTopicTitles[topic],body,status,audience:T('متقاضی بین‌المللی؛ شرایط تابع تابعیت، دوره و نوع مجوز است.','International applicants; conditions depend on nationality, programme and permit.','Uluslararası başvurular; koşullar uyruğa, programa ve izne bağlıdır.'),source_title:source.title,source_url:source.url,source_type:status==='planning'?'planning':source.type||'government',verified_at:day,last_updated:day,jurisdiction:source.jurisdiction||seed.jurisdiction?.en||seed.name.en,verified_by:'Creator Group automated official-source review',created_at:day,updated_at:day};}
const seeds:Seed[]=[
 {code:'TR',slug:'turkiye',name:T('ترکیه','Türkiye','Türkiye'),capital:T('آنکارا','Ankara','Ankara'),language:[T('ترکی','Turkish','Türkçe')],currency:'TRY',zone:['Europe/Istanbul'],cities:[T('استانبول','Istanbul','İstanbul'),T('آنکارا','Ankara','Ankara'),T('ازمیر','Izmir','İzmir')],lat:39.93,lng:32.86,overview:T('دانشگاه، شهر و زندگی در ترکیه را کنار مسیر اقامت بررسی کنید.','Explore universities, cities and life in Türkiye alongside residence planning.','Türkiye’de üniversiteleri, şehirleri ve yaşamı ikamet planlamasıyla keşfedin.'),source:sources.trStudy},
 {code:'DE',slug:'germany',name:T('آلمان','Germany','Almanya'),capital:T('برلین','Berlin','Berlin'),language:[T('آلمانی','German','Almanca')],currency:'EUR',zone:['Europe/Berlin'],cities:[T('برلین','Berlin','Berlin'),T('مونیخ','Munich','Münih'),T('هامبورگ','Hamburg','Hamburg')],lat:52.52,lng:13.4,overview:T('مسیر تحصیل و گزینه‌های بعد از دانشگاه را از منابع دولت آلمان ببینید.','Explore study and graduate options through German government sources.','Alman hükûmeti kaynaklarıyla eğitim ve mezuniyet seçeneklerini inceleyin.'),source:sources.deStudy},
 {code:'NL',slug:'netherlands',name:T('هلند','Netherlands','Hollanda'),capital:T('آمستردام','Amsterdam','Amsterdam'),language:[T('هلندی','Dutch','Felemenkçe')],currency:'EUR',zone:['Europe/Amsterdam'],cities:[T('آمستردام','Amsterdam','Amsterdam'),T('روتردام','Rotterdam','Rotterdam'),T('اوترخت','Utrecht','Utrecht')],lat:52.37,lng:4.9,overview:T('حمایت دانشگاه، پیشرفت تحصیلی و گزینه‌های فارغ‌التحصیل را با منابع IND بررسی کنید.','Explore institution sponsorship, study progress and graduate options with IND sources.','IND kaynaklarıyla kurum sponsorluğunu, eğitim ilerlemesini ve mezuniyet seçeneklerini inceleyin.'),source:sources.nlStudy},
 {code:'CY',slug:'cyprus',name:T('قبرس','Cyprus','Kıbrıs'),capital:T('نیکوزیا','Nicosia','Lefkoşa'),language:[T('یونانی','Greek','Yunanca'),T('ترکی','Turkish','Türkçe')],currency:'EUR',zone:['Asia/Nicosia'],cities:[T('نیکوزیا','Nicosia','Lefkoşa'),T('لیماسول','Limassol','Limasol'),T('لارناکا','Larnaca','Larnaka')],lat:35.17,lng:33.36,jurisdiction:T('مناطق تحت کنترل دولت جمهوری قبرس؛ قواعد شمال قبرس جدا هستند.','Republic of Cyprus government-controlled areas; northern Cyprus rules are separate.','Kıbrıs Cumhuriyeti hükûmetinin kontrolündeki bölgeler; Kuzey Kıbrıs kuralları ayrıdır.'),overview:T('راهنمای این صفحه فقط برای جمهوری قبرس است؛ حوزهٔ دانشگاه را پیش از اقدام مشخص کنید.','This guide covers the Republic of Cyprus. Confirm your university jurisdiction before proceeding.','Bu rehber Kıbrıs Cumhuriyeti’ni kapsar. İşlem öncesi üniversitenizin yetki alanını doğrulayın.'),source:sources.cyStudy},
 {code:'CN',slug:'china',name:T('چین','China','Çin'),capital:T('پکن','Beijing','Pekin'),language:[T('چینی معیار','Standard Chinese','Standart Çince')],currency:'CNY',zone:['Asia/Shanghai'],cities:[T('پکن','Beijing','Pekin'),T('شانگهای','Shanghai','Şanghay'),T('گوانگژو','Guangzhou','Guangzhou')],lat:39.9,lng:116.4,jurisdiction:T('چینِ سرزمین اصلی؛ روندهای محلی پکن با برچسب جدا مشخص شده‌اند.','Mainland China; Beijing-specific procedures are labelled separately.','Çin ana karası; Pekin’e özgü işlemler ayrıca belirtilir.'),overview:T('ویزای تحصیلی و مجوزهای محلی را همراه دانشگاه مقصد بررسی کنید.','Explore study visas and local permissions with your host institution.','Eğitim vizesini ve yerel izinleri ev sahibi kurumunuzla inceleyin.'),source:sources.cnVisa},
 {code:'RU',slug:'russia',name:T('روسیه','Russia','Rusya'),capital:T('مسکو','Moscow','Moskova'),language:[T('روسی','Russian','Rusça')],currency:'RUB',zone:['Europe/Moscow','Asia/Vladivostok'],cities:[T('مسکو','Moscow','Moskova'),T('سن‌پترزبورگ','Saint Petersburg','Sankt Peterburg'),T('کازان','Kazan','Kazan')],lat:55.75,lng:37.62,overview:T('دوره، زبان آموزش و وضعیت رسمی دانشگاه را در پورتال تحصیل در روسیه بررسی کنید.','Explore programmes, teaching language and institutions through Study in Russia.','Study in Russia üzerinden programları, eğitim dilini ve kurumları inceleyin.'),source:sources.ruStudy},
 {code:'ES',slug:'spain',name:T('اسپانیا','Spain','İspanya'),capital:T('مادرید','Madrid','Madrid'),language:[T('اسپانیایی','Spanish','İspanyolca')],currency:'EUR',zone:['Europe/Madrid','Atlantic/Canary'],cities:[T('مادرید','Madrid','Madrid'),T('بارسلونا','Barcelona','Barselona'),T('والنسیا','Valencia','Valensiya')],lat:40.42,lng:-3.7,overview:T('تحصیل، اجازهٔ کار و اقامت پس از تحصیل را به‌عنوان درخواست‌های مشروط بررسی کنید.','Explore study, employment permission and graduate residence as conditional applications.','Eğitim, çalışma izni ve mezuniyet ikametini koşullu başvurular olarak inceleyin.'),source:sources.esStudy},
];
function intelligence(seed:Seed){const blocks=new Map<CountryTopic,CountryIntelligence>();
 const pending=T('جزئیات قابل‌اتکا برای این مسیر هنوز تأیید نشده؛ نوع دوره، تابعیت و مرجع مسئول باید بررسی شوند.','Reliable details for this route are not yet verified. Programme, nationality and competent authority need review.','Bu rota için güvenilir ayrıntılar henüz doğrulanmadı. Program, uyruk ve yetkili makam incelenmeli.');
 for(const topic of countryTopics)blocks.set(topic,block(seed,topic,pending,seed.source,'needs-verification'));
 const set=(topic:CountryTopic,body:ReturnType<typeof T>,source?:Source,status:CountryIntelligence['status']='verified')=>blocks.set(topic,block(seed,topic,body,source,status));
 set('overview',seed.overview,seed.source,'planning');
 set('livingCosts',T('بودجهٔ شهر شامل مسکن، ودیعه، خوراک، حمل‌ونقل و بیمه است. مبلغ جاریِ تأییدشده برای این شهر در کاتالوگ ثبت نشده.','Plan housing, deposits, food, transport and insurance. A verified current city budget is not yet recorded in this catalogue.','Konaklama, depozito, yemek, ulaşım ve sigortayı planlayın. Bu katalogda doğrulanmış güncel şehir bütçesi henüz yok.'),seed.source,'planning');
 set('returnHome',T('برای بازگشت، اعتبار مدرک در کشور خود، مجوز شغل‌های تخصصی و مدارک ترجمه را جدا بررسی کنید. نتیجه بدون مشخص شدن کشور بازگشت قابل تأیید نیست.','For returning home, check degree recognition, regulated-profession licensing and translated records in your home country. An outcome cannot be verified without that country.','Dönüş için kendi ülkenizde diploma tanınmasını, düzenlenmiş meslek izinlerini ve tercümeleri inceleyin. Dönüş ülkesi bilinmeden sonuç doğrulanamaz.'),seed.source,'needs-verification');
 if(seed.code==='TR'){
 set('study',T('زبان، شرایط پذیرش و اعتبار دوره را در اطلاعات رسمی همان دانشگاه بررسی کنید.','Check programme language, entry requirements and accreditation with the university.','Program dili, kabul koşulları ve akreditasyonu üniversiteden doğrulayın.'),sources.trStudy);
 set('visa',T('قواعد ورود تحصیلی با گردشگری فرق دارد؛ سفارت ترکیه باید وضعیت تابعیت شما را بررسی کند.','Education entry rules differ from tourism; check nationality requirements with the Turkish mission.','Eğitim giriş kuralları turizmden farklıdır; uyruğunuza göre Türk temsilciliğine danışın.'),sources.trVisa);
 set('residence',T('برای تحصیلات عالی، اقامت دانشجویی مسیر جداگانه‌ای با شرایط و مدارک رسمی دارد.','Higher education has a student residence route with official conditions and documents.','Yükseköğretim için resmî koşul ve belgelerle öğrenci ikameti yolu bulunur.'),sources.trResidence);
 set('studentWork',T('کار نیازمند مجوز کار است؛ حق کار دانشجوی کاردانی و کارشناسی بعد از سال اول شروع می‌شود.','Work requires a work permit; associate and undergraduate students qualify after their first year.','Çalışma izni gerekir; ön lisans ve lisans öğrencileri için çalışma hakkı ilk yıldan sonra başlar.'),sources.trWork);
 set('afterGraduation',T('دانش‌آموختگان می‌توانند ظرف شش ماه برای اقامت کوتاه‌مدتِ یک‌باره تا یک سال درخواست دهند؛ پذیرش مشروط است.','Graduates may apply within six months for a one-off short-term permit up to one year; approval is conditional.','Mezunlar altı ay içinde bir defalık, en fazla bir yıllık kısa dönem izin için başvurabilir; onay koşulludur.'),sources.trResidence);
 set('permanentResidence',T('اقامت بلندمدت عموماً هشت سال اقامت پیوسته و شرایط دیگر می‌خواهد؛ زمان اقامت دانشجویی نصف محاسبه می‌شود.','Long-term residence generally requires eight continuous years and other conditions; student residence time counts at half.','Uzun dönem ikamet genellikle sekiz yıl kesintisiz ikamet ve ek koşullar gerektirir; öğrenci ikameti yarım hesaplanır.'),sources.trResidence);
 set('citizenship',T('تابعیت تصمیمی جدا بر پایهٔ قانون ۵۹۰۱ است؛ تحصیل به‌تنهایی تابعیت ایجاد نمی‌کند.','Citizenship is a separate decision under Law 5901; study alone does not confer citizenship.','Vatandaşlık 5901 sayılı kanuna göre ayrı bir karardır; eğitim tek başına vatandaşlık sağlamaz.'),sources.trCitizen);
 }
 if(seed.code==='DE'){
 set('study',T('پذیرش دوره و تأمین مالی برای مسیر تحصیل مهم‌اند؛ زبان و مدارک وابسته به دوره است.','Admission and financing matter for the study route; language and documents depend on the programme.','Eğitim yolunda kabul ve finansman önemlidir; dil ve belgeler programa bağlıdır.'),sources.deStudy);
 set('visa',T('متقاضیان خارج از اتحادیهٔ اروپا باید لزوم ویزا را با نمایندگی آلمان بررسی کنند.','Non-EU applicants should check visa requirements with the German mission.','AB dışından başvuranlar vize gerekliliğini Alman temsilciliğiyle doğrulamalı.'),sources.deStudy);
 set('residence',T('اجازهٔ اقامت تحصیلی مشروط به شرایط دوره و تأمین معیشت است؛ تمدید نیازمند بررسی است.','Study residence is conditional on programme requirements and financing; extensions need assessment.','Eğitim ikameti program koşullarına ve geçime bağlıdır; uzatma değerlendirme gerektirir.'),sources.deStudy);
 set('studentWork',T('دانشجویان کشورهای ثالث تا ۱۴۰ روز کامل یا ۲۸۰ نیم‌روز سالانه می‌توانند کار کنند؛ قواعد جایگزین و استثناها را بررسی کنید.','Third-country students may work 140 full or 280 half days yearly; check alternative counting rules and exceptions.','Üçüncü ülke öğrencileri yılda 140 tam veya 280 yarım gün çalışabilir; alternatif hesaplama ve istisnaları inceleyin.'),sources.deWork);
 set('afterGraduation',T('پس از پایان موفق تحصیل، امکان درخواست اقامت جست‌وجوی کار تا ۱۸ ماه با شرایط مالی و بیمه وجود دارد.','After successful graduation, an up-to-18-month job-search permit may be requested, subject to funding and insurance conditions.','Başarılı mezuniyet sonrası, finansman ve sigorta koşullarıyla 18 aya kadar iş arama izni istenebilir.'),sources.deAfter);
 set('permanentResidence',T('دانش‌آموختگان آلمان ممکن است پس از دو سال اقامت کاریِ تخصصی، ۲۴ ماه بیمه بازنشستگی و شرایط زبان و معیشت درخواست دهند.','German graduates may apply after two years of skilled-work residence, 24 months of pension contributions and language/livelihood conditions.','Almanya mezunları iki yıllık nitelikli çalışma ikameti, 24 aylık emeklilik primi ve dil/geçim koşullarıyla başvurabilir.'),sources.dePR);
 set('citizenship',T('شرایط تابعیت از اقامت تحصیلی جداست؛ نوع اقامت فعلی، زبان و دیگر شرایط قانونی باید بررسی شوند.','Naturalisation conditions are separate from study residence; current residence type, language and other legal requirements need assessment.','Vatandaşlık koşulları eğitim ikametinden ayrıdır; mevcut ikamet türü, dil ve diğer yasal koşullar incelenmeli.'),sources.deCitizen,'needs-verification');
 }
 if(seed.code==='NL'){
 set('study',T('مؤسسه باید حامی مورد تأیید IND و دوره تمام‌وقتِ معتبر باشد؛ پیشرفت تحصیلی سنجیده می‌شود.','The institution must be an IND recognised sponsor with an accredited full-time programme; study progress is assessed.','Kurum IND tarafından tanınan sponsor, program akredite ve tam zamanlı olmalı; eğitim ilerlemesi değerlendirilir.'),sources.nlStudy);
 set('visa',T('مؤسسهٔ حامی درخواست اقامت و در صورت نیاز MVV را هماهنگ می‌کند؛ لزوم ویزا به تابعیت بستگی دارد.','The sponsoring institution coordinates residence and, where needed, MVV; visa requirements depend on nationality.','Sponsor kurum ikameti ve gerekirse MVV’yi koordine eder; vize gerekliliği uyruğa bağlıdır.'),sources.nlStudy);
 set('residence',T('درخواست دانشجویی از طریق مؤسسهٔ مورد تأیید انجام می‌شود؛ حفظ شرایط دوره برای اعتبار مجوز ضروری است.','The recognised institution submits the student application; continued programme eligibility is required for the permit.','Tanınan kurum öğrenci başvurusunu yapar; iznin geçerliliği için eğitim koşulları korunmalı.'),sources.nlStudy);
 set('studentWork',T('برای کار استخدامی، کارفرما TWV می‌خواهد: تا ۱۶ ساعت هفتگی یا تمام‌وقت در ژوئن، ژوئیه و اوت.','Employee work requires employer TWV: up to 16 hours weekly OR full-time in June, July and August.','Ücretli iş için işverenin TWV izni gerekir: haftada 16 saat VEYA haziran, temmuz ve ağustosta tam zamanlı.'),sources.nlStudy);
 set('afterGraduation',T('فارغ‌التحصیلان واجد شرایط می‌توانند ظرف سه سال برای سال جهت‌یابی درخواست دهند؛ شرایط مدرک و سابقه باید بررسی شود.','Eligible graduates may apply for an orientation year within three years; qualification and previous-use conditions apply.','Uygun mezunlar üç yıl içinde oryantasyon yılına başvurabilir; diploma ve önceki kullanım koşulları geçerlidir.'),sources.nlAfter);
 set('permanentResidence',T('تحصیل و سال جهت‌یابی هدف اقامت موقت‌اند؛ درخواست وضعیت پایدارتر نیاز به هدف غیرموقت و شرایط دیگر دارد.','Study and orientation year are temporary residence purposes; a more secure status requires a non-temporary purpose and other conditions.','Eğitim ve oryantasyon yılı geçici ikamet amaçlarıdır; daha kalıcı statü için geçici olmayan amaç ve ek koşullar gerekir.'),sources.nlPurpose);
 set('citizenship',T('تابعیت خودکار پس از دانشگاه وجود ندارد؛ مدت اقامت، نوع مجوز، ادغام و استثناها را IND بررسی می‌کند.','Graduation does not automatically confer citizenship; IND assesses residence duration, permit type, integration and exceptions.','Mezuniyet otomatik vatandaşlık sağlamaz; IND ikamet süresini, izin türünü, uyumu ve istisnaları değerlendirir.'),sources.nlCitizen);
 }
 if(seed.code==='CY'){
 set('study',T('پذیرش در دوره و مؤسسهٔ واجد شرایط باید مطابق راهنمای رسمی جمهوری قبرس بررسی شود.','Programme and institution eligibility must be checked against Republic of Cyprus guidance.','Program ve kurum uygunluğu Kıbrıs Cumhuriyeti’nin resmî rehberine göre doğrulanmalı.'),sources.cyStudy);
 set('visa',T('شرایط ورود و درخواست دانشجوییِ اتباع کشورهای ثالث در راهنمای ادارهٔ مهاجرت مشخص می‌شود.','Third-country entry and student application conditions are set out by the Migration Department.','Üçüncü ülke giriş ve öğrenci başvuru koşulları Göç Dairesi rehberinde açıklanır.'),sources.cyStudy);
 set('residence',T('مجوز دانشجویی تا یک سال و قابل تمدید با حفظ شرایط قانونی است.','A student permit may be issued for up to one year and renewed while legal conditions remain met.','Öğrenci izni bir yıla kadar verilebilir ve yasal koşullar sürdükçe yenilenebilir.'),sources.cyStudy);
 set('studentWork',T('در چارچوب فعالیت‌های مجاز: حداکثر ۲۰ ساعت هفتگی هنگام تحصیل و ۳۸ ساعت در تعطیلی کلاس‌ها.','Within permitted activities: up to 20 hours weekly during study and 38 hours during class breaks.','İzin verilen faaliyetlerde: eğitim sırasında haftada 20, ders aralarında 38 saate kadar.'),sources.cyWork);
 set('afterGraduation',T('با احراز شرایط، امکان درخواست اقامت جست‌وجوی کار یا کسب‌وکار تا ۱۲ ماه پس از تحصیل وجود دارد.','Subject to eligibility, a post-study job-search or entrepreneurship residence permit may be requested for up to 12 months.','Uygunluk koşullarıyla mezuniyet sonrası iş arama veya girişimcilik ikameti en fazla 12 ay için istenebilir.'),sources.cyStudy);
 set('permanentResidence',T('اقامت بلندمدت شرایط مستقلی دارد؛ نحوهٔ شمارش اقامت دانشجویی و استثناهای پرونده نیازمند تأیید ادارهٔ مهاجرت است.','Long-term residence has separate requirements; student-time counting and case-specific exclusions need Migration Department confirmation.','Uzun dönem ikamet ayrı koşullara bağlıdır; öğrencilik süresinin hesabı ve dosya istisnaları Göç Dairesinden doğrulanmalı.'),sources.cyPR,'needs-verification');
 set('citizenship',T('فرم M127 شرایط اقامت، زبان یونانی و دیگر الزامات را تعیین می‌کند؛ تحصیل به‌تنهایی تابعیت ایجاد نمی‌کند.','Form M127 sets residence, Greek-language and other requirements; study alone does not confer citizenship.','M127 formu ikamet, Yunanca ve ek koşulları belirler; eğitim tek başına vatandaşlık sağlamaz.'),sources.cyCitizen);
 }
 if(seed.code==='CN'){
 set('study',T('پذیرش، زبان و مدارک دوره باید با دانشگاه میزبان تأیید شود؛ فهرست دانشگاه‌های ما برای چین هنوز منتشر نشده.','Confirm admission, language and programme documents with the host institution; our China university catalogue is not yet published.','Kabul, dil ve program belgelerini ev sahibi kurumla doğrulayın; Çin üniversite kataloğumuz henüz yayımlanmadı.'),sources.cnVisa,'planning');
 set('visa',T('X1 برای تحصیل بیش از ۱۸۰ روز و X2 برای تحصیل کوتاه‌تر است؛ مدارک کنسولی را بررسی کنید.','X1 is for study over 180 days, X2 for shorter study; check consular documents.','X1 180 günden uzun, X2 daha kısa eğitim içindir; konsolosluk belgelerini inceleyin.'),sources.cnVisa);
 set('residence',T('برای پکن، راهنمای رسمی مدارک اقامت تحصیلی و ثبت اقامت را مشخص می‌کند؛ روند شهر مقصد را تأیید کنید.','Beijing guidance lists study-residence documents and accommodation registration; verify the procedure in your destination city.','Pekin rehberi eğitim ikameti belgelerini ve konaklama kaydını açıklar; hedef şehir işlemini doğrulayın.'),sources.cnResidence);
 set('studentWork',T('در پکن، کار یا کارآموزی خارج از دانشگاه نیازمند موافقت دانشگاه و درج مجوز در اقامت تحصیلی است.','In Beijing, off-campus work-study or internship requires institution approval and a residence-permit endorsement.','Pekin’de kampüs dışı çalışma veya staj için kurum onayı ve ikamet iznine şerh gerekir.'),sources.cnResidence);
 }
 if(seed.code==='RU'){
 set('study',T('بسیاری از دوره‌ها روسی‌اند؛ زبان آموزش و دورهٔ آمادگی را با دانشگاه مقصد بررسی کنید.','Many programmes use Russian; check teaching language and preparatory study with the institution.','Birçok program Rusçadır; eğitim dilini ve hazırlığı kurumdan doğrulayın.'),sources.ruStudy);
 set('visa',T('لزوم ویزا و دعوت‌نامه باید با دانشگاه میزبان و کنسولگری روسیه مطابق تابعیت بررسی شود.','Check visa and invitation requirements with the host institution and Russian consulate for your nationality.','Uyruk bazında vize ve davetiye gerekliliğini kurum ve Rus konsolosluğuyla doğrulayın.'),sources.ruStudy,'needs-verification');
 set('studentWork',T('دانشجوی تمام‌وقتِ دانشگاه دارای اعتبار دولتی می‌تواند در وقت آزاد بدون مجوز کار فعالیت کند؛ گواهی تحصیل لازم است.','Full-time students at state-accredited institutions may work in free time without a work permit; proof of study is required.','Devlet akreditasyonlu kurumların tam zamanlı öğrencileri boş zamanda çalışma izinsiz çalışabilir; öğrenci belgesi gerekir.'),sources.ruStudy);
 }
 if(seed.code==='ES'){
 set('study',T('اعتبار مؤسسه و نوع تحصیل، شرایط ورود و درخواست اقامت آموزشی را تعیین می‌کنند.','Institution accreditation and study type determine study-entry and authorisation requirements.','Kurum akreditasyonu ve eğitim türü giriş ve eğitim izni koşullarını belirler.'),sources.esStudy,'planning');
 set('studentWork',T('اجازهٔ تحصیلات عالی می‌تواند کار سازگار با تحصیل را خودکار مجاز کند؛ معمولاً سقف ۳۰ ساعت هفتگی دارد و استثناها باید بررسی شوند.','Higher-education authorisation can automatically permit compatible work, generally capped at 30 hours weekly; exceptions need review.','Yükseköğretim izni eğitimle uyumlu çalışmayı otomatik sağlayabilir; genellikle haftada 30 saat sınırı vardır, istisnalar incelenmeli.'),sources.esWork);
 set('afterGraduation',T('واجدان شرایط می‌توانند اقامت جست‌وجوی کار تا ۲۴ ماه درخواست دهند؛ این مجوز به‌تنهایی اجازهٔ کار نمی‌دهد.','Eligible graduates may request job-search residence for up to 24 months; that permit itself does not authorise work.','Uygun mezunlar 24 aya kadar iş arama ikameti isteyebilir; bu izin tek başına çalışma hakkı sağlamaz.'),sources.esAfter);
 }
 return [...blocks.values()];
}
export const countrySeeds:Country[]=seeds.map(s=>countrySchema.parse({code:s.code,slug:s.slug,published:true,name:s.name,capital:s.capital,languages:s.language,currency:s.currency,timeZones:s.zone,cities:s.cities,jurisdiction:s.jurisdiction||s.name,overview:s.overview,coordinates:{lat:s.lat,lng:s.lng},heroImage:s.code==='TR'?'/images/universities/atlas.webp':'/images/earth/earth-day.webp',heroCredit:s.code==='TR'?T('دانشگاه اطلس، استانبول — عکس واقعی دانشگاه','Atlas University, Istanbul — actual campus photograph','Atlas Üniversitesi, İstanbul — gerçek kampüs fotoğrafı'):T('تصویر ماهواره‌ای زمین؛ نمای کشور نیست.','Satellite Earth imagery; not a country photograph.','Dünya uydu görüntüsü; ülke fotoğrafı değildir.'),intelligence:intelligence(s),created_at:day,updated_at:day}));
