import {z} from 'zod';
export const countryTopics=['overview','study','visa','residence','studentWork','afterGraduation','returnHome','permanentResidence','citizenship','livingCosts'] as const;
export type CountryTopic=typeof countryTopics[number];
export const countryText=z.object({fa:z.string().max(10000),en:z.string().max(10000),tr:z.string().max(10000)});
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>{const n=Date.parse(v+'T00:00:00Z');return Number.isFinite(n)&&new Date(n).toISOString().slice(0,10)===v;},'Use a real calendar date');
const source=z.object({source_title:z.string().min(3).max(500),source_url:z.string().url().refine(v=>v.startsWith('https://'),'Use an HTTPS source'),source_type:z.enum(['government','official-education','university','planning']),verified_at:date,last_updated:date,jurisdiction:z.string().min(2).max(300),verified_by:z.string().min(2).max(150),created_at:date,updated_at:date});
export const intelligenceSchema=source.extend({topic:z.enum(countryTopics),title:countryText,body:countryText,status:z.enum(['verified','needs-verification','planning']),audience:countryText});
export const countrySchema=z.object({code:z.string().regex(/^[A-Z]{2}$/),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),published:z.boolean(),name:countryText,capital:countryText,languages:z.array(countryText).max(10),currency:z.string().regex(/^[A-Z]{3}$/),timeZones:z.array(z.string().max(80)).max(15),cities:z.array(countryText).max(20),jurisdiction:countryText,overview:countryText,coordinates:z.object({lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)}),heroImage:z.string().max(2000).refine(v=>/^https:\/\//.test(v)||/^\/images\/[a-zA-Z0-9/_.-]+$/.test(v)),heroCredit:countryText,intelligence:z.array(intelligenceSchema).max(30),created_at:date,updated_at:date}).refine(c=>new Set(c.intelligence.map(b=>b.topic)).size===c.intelligence.length,'Each intelligence topic must be unique');
export type Country=z.infer<typeof countrySchema>;
export type CountryIntelligence=z.infer<typeof intelligenceSchema>;
export function countrySourceFresh(block:CountryIntelligence,now=new Date()){const days=(now.getTime()-Date.parse(block.verified_at+'T00:00:00Z'))/86400000;return block.status==='verified'&&days>=-1&&days<=90;}
export const countryTopicTitles:Record<CountryTopic,z.infer<typeof countryText>>={overview:{fa:'شناخت کشور',en:'Country overview',tr:'Ülkeyi tanıyın'},study:{fa:'تحصیل',en:'Study',tr:'Eğitim'},visa:{fa:'ویزای ورود',en:'Entry visa',tr:'Giriş vizesi'},residence:{fa:'اقامت دانشجویی',en:'Student residence',tr:'Öğrenci ikameti'},studentWork:{fa:'کار دانشجویی',en:'Student work',tr:'Öğrenciyken çalışma'},afterGraduation:{fa:'پس از فارغ‌التحصیلی',en:'After graduation',tr:'Mezuniyet sonrası'},returnHome:{fa:'بازگشت به کشور خود',en:'Returning home',tr:'Ülkenize dönüş'},permanentResidence:{fa:'اقامت بلندمدت',en:'Long-term residence',tr:'Uzun dönem ikamet'},citizenship:{fa:'تابعیت',en:'Citizenship',tr:'Vatandaşlık'},livingCosts:{fa:'بودجهٔ زندگی',en:'Living budget',tr:'Yaşam bütçesi'}};
export function countryAnswer(country:Country,question:string,lang:'fa'|'en'|'tr',now=new Date()){
 const q=question.normalize('NFKC').toLocaleLowerCase('tr').replace(/[ي]/g,'ی').replace(/[ك]/g,'ک');
 const terms:Record<CountryTopic,string[]>={overview:['overview','capital','currency','پایتخت','واحد پول','para birimi','başkent'],study:['study','university','admission','تحصیل','دانشگاه','eğitim','üniversite'],visa:['visa','ویزا','vize'],residence:['residence permit','student residence','اقامت دانشجویی','ikamet'],studentWork:['work','job','کار','çalış','iş'],afterGraduation:['graduat','after study','فارغ','پس از تحصیل','mezun'],returnHome:['return','home','بازگشت','برگشت','dönüş'],permanentResidence:['permanent','long-term','بلندمدت','دائم','uzun dönem','kalıcı'],citizenship:['citizen','nationality','تابعیت','شهروند','vatandaş'],livingCosts:['cost','budget','rent','هزینه','بودجه','اجاره','maliyet','bütçe','kira']};
 // Specific questions win over words such as "work after graduation".
 const priority:CountryTopic[]=['citizenship','permanentResidence','afterGraduation','returnHome','studentWork','visa','residence','livingCosts','study','overview'];
 const topic=priority.find(t=>terms[t].some(term=>q.includes(term)));
 const block=topic?country.intelligence.find(b=>b.topic===topic):undefined;
 const unknown={fa:'این پرسش به بررسی شرایط شخصی و منبع رسمی بیشتری نیاز دارد. موضوع ویزا، کار، هزینه یا پس از تحصیل را انتخاب کنید.',en:'This question needs personal circumstances and further official verification. Choose visa, work, budget or after graduation.',tr:'Bu soru kişisel koşulların ve resmî kaynakların incelenmesini gerektiriyor. Vize, çalışma, bütçe veya mezuniyet sonrasını seçin.'};
 const stale={fa:'منبع این بخش باید دوباره بررسی شود؛ پاسخ قطعی برای پروندهٔ شما در دسترس نیست.',en:'This source needs another review; a definitive answer for your case is unavailable.',tr:'Bu kaynak yeniden incelenmeli; dosyanız için kesin yanıt mevcut değil.'};
 return {mode:'official-source-retrieval' as const,topic:topic||null,answer:block?(countrySourceFresh(block,now)?block.body[lang]:block.body[lang]+' '+stale[lang]):unknown[lang],source:block?{title:block.source_title,url:block.source_url,verified_at:block.verified_at,jurisdiction:block.jurisdiction,status:block.status}:null,personalAssessmentRequired:true};
}
