import 'server-only';
import {existsSync} from 'node:fs';
import {resolve} from 'node:path';
import {getRawDb} from '@/db/raw';
import {digest,sameOrigin} from './request-security';
export {sameOrigin};
const cookie=(r:Request,name:string)=>r.headers.get('cookie')?.split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)||'';
export async function student(r:Request){const token=cookie(r,'creator_student');if(!/^[a-f0-9]{64}$/.test(token))return null;return getRawDb().prepare('SELECT a.id,a.name,a.email FROM student_sessions s JOIN student_accounts a ON a.id=s.student_id WHERE s.token_hash=? AND s.expires_at>?').bind(await digest(token),Date.now()).first<{id:string,name:string,email:string}>();}
export async function isAdmin(r:Request){const token=cookie(r,'creator_admin');if(!/^[a-f0-9]{64}$/.test(token))return false;return !!await getRawDb().prepare('SELECT token_hash FROM admin_sessions WHERE token_hash=? AND expires_at>?').bind(await digest(token),Date.now()).first();}
export async function newSession(id:string|null){const bytes=crypto.getRandomValues(new Uint8Array(32));const token=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');const db=getRawDb();const ttl=id?14*86400:8*3600;if(id)await db.prepare('INSERT INTO student_sessions(token_hash,student_id,expires_at) VALUES(?,?,?)').bind(await digest(token),id,Date.now()+ttl*1000).run();else await db.prepare('INSERT INTO admin_sessions(token_hash,expires_at) VALUES(?,?)').bind(await digest(token),Date.now()+ttl*1000).run();return `${id?'creator_student':'creator_admin'}=${token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${ttl}${process.env.NODE_ENV==='production'?'; Secure':''}`;}
export async function logout(r:Request,admin=false){const name=admin?'creator_admin':'creator_student';const token=cookie(r,name);if(token)await getRawDb().prepare(`DELETE FROM ${admin?'admin_sessions':'student_sessions'} WHERE token_hash=?`).bind(await digest(token)).run();return `${name}=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${process.env.NODE_ENV==='production'?'; Secure':''}`;}
export async function hashPassword(password:string,salt?:string){salt=salt||Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:new TextEncoder().encode(salt),iterations:250000},key,256);return salt+':'+Array.from(new Uint8Array(bits),b=>b.toString(16).padStart(2,'0')).join('');}
export async function limited(r:Request,scope:string,max=30,window=600000){const ip=r.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';const key=await digest(`${scope}:${ip}`),db=getRawDb(),now=Date.now();await db.prepare('INSERT INTO platform_rate_limits(key,count,expires_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN expires_at<? THEN 1 ELSE count+1 END,expires_at=CASE WHEN expires_at<? THEN excluded.expires_at ELSE expires_at END').bind(key,now+window,now,now).run();const row=await db.prepare('SELECT count FROM platform_rate_limits WHERE key=?').bind(key).first<{count:number}>();return (row?.count||0)>max;}
export async function readJSON(r:Request,max=1200000){const reader=r.body?.getReader();if(!reader)throw Error('Empty body');let total=0;const chunks:Uint8Array[]=[];while(true){const p=await reader.read();if(p.done)break;total+=p.value.byteLength;if(total>max){await reader.cancel();throw Error('Body too large');}chunks.push(p.value);}const result=new Uint8Array(total);let off=0;for(const c of chunks){result.set(c,off);off+=c.length;}return JSON.parse(new TextDecoder().decode(result));}
export async function audit(action:string,id:string,details:Record<string,unknown>={}){await getRawDb().prepare('INSERT INTO admin_audit(id,action,entity_id,details,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),action,id,JSON.stringify(details),Date.now()).run();}

export function loadPlatformEnvironment(){const file=resolve(process.env.CREATOR_DATA_DIR||'./data','creator.env');if(existsSync(file))process.loadEnvFile(file);}
