const T=(fa:string,en:string,tr:string)=>({fa,en,tr});
/** Planning questions, not legal conclusions. Country rules appear separately with sources. */
export const returnScenarios=[
 {key:'temporary',title:T('بازگشت موقت به خانه','Temporarily return home','Geçici olarak ülkenize dönüş'),body:T('پیش از خروج، اعتبار گذرنامه، ویزا یا اقامت و شرایط ورود دوباره را با مرجع کشور مقصد بررسی کن. از دانشگاه تأیید بگیر که غیبت، حضور در کلاس و امتحان را تحت تأثیر نمی‌گذارد. طول سفر و نوع مجوز را اعلام کن؛ پاسخ برای همه یکسان نیست.','Before leaving, check passport, visa/permit validity and re-entry conditions with the destination authority. Ask your university about attendance and exams. State your absence length and permit type; there is no universal answer.','Çıkıştan önce pasaport, vize/ikamet geçerliliğini ve yeniden giriş koşullarını yetkili makamla doğrulayın. Devam ve sınavları üniversitenize sorun. Yokluk süresi ve izin türünü belirtin; herkes için aynı yanıt yoktur.')},
 {key:'continue',title:T('ادامهٔ تحصیل پس از بازگشت','Continue studying after returning','Dönüşten sonra eğitime devam'),body:T('از دانشگاه دربارهٔ مرخصی تحصیلی، ادامهٔ ثبت‌نام و زمان بازگشت پاسخ کتبی بخواه. حفظ ثبت‌نام الزاماً به معنای معتبر ماندن اقامت نیست؛ اثر غیبت و امکان تمدید را از ادارهٔ مهاجرت جدا بررسی کن.','Ask the university for written leave, continued-enrolment and return-date arrangements. Remaining enrolled does not necessarily preserve residence permission. Check absence and renewal consequences separately with immigration authorities.','İzin, kayıt devamı ve dönüş tarihi için üniversiteden yazılı bilgi alın. Kayıtlı olmak ikamet iznini mutlaka korumaz. Yokluk ve uzatma sonuçlarını göç makamından ayrıca doğrulayın.')},
 {key:'withdraw',title:T('انصراف یا توقف تحصیل','Withdraw or pause your studies','Eğitimden ayrılma veya ara verme'),body:T('روند انصراف، شرایط بازپرداخت و دسترسی به ریزنمرات را در قرارداد و مقررات دانشگاه بررسی کن. پایان وضعیت دانشجویی ممکن است بر مبنای اقامت اثر بگذارد؛ پیش از اقدام، مهلت و تکلیف اطلاع‌رسانی را از مرجع رسمی بپرس.','Check withdrawal, refund conditions and transcript access in your university agreement. Ending student status may affect the basis for residence. Ask the authority about deadlines and notification duties before acting.','Ayrılma, iade koşulları ve transkript erişimini üniversite sözleşmesinden kontrol edin. Öğrenciliğin bitmesi ikamet gerekçesini etkileyebilir. İşlem öncesi süreleri ve bildirim yükümlülüklerini yetkili makama sorun.')},
 {key:'graduate',title:T('فارغ‌التحصیلی و بازگشت به خانه','Graduate and return home','Mezuniyet ve ülkenize dönüş'),body:T('دریافت مدرک، ریزنمرات رسمی، ترجمه و تأییدات لازم را پیش از خروج برنامه‌ریزی کن. اعتبار مدرک و مجوز کار در حرفه‌هایی مثل پزشکی و دندان‌پزشکی به مقررات کشور بازگشت وابسته است؛ پذیرش دانشگاه، معادل‌سازی مدرک را تضمین نمی‌کند.','Plan diploma, official transcripts, translations and required legalisation before leaving. Degree recognition and licensing in regulated professions such as medicine and dentistry depend on your home country. Admission does not guarantee recognition.','Çıkış öncesi diploma, resmî transkript, tercüme ve gerekli tasdikleri planlayın. Tıp ve diş hekimliği gibi mesleklerde denklik ve çalışma ruhsatı dönüş ülkesine bağlıdır. Üniversite kabulü denklik garantisi değildir.')},
 {key:'reentry',title:T('بازگشت دوباره به کشور مقصد','Return to this country later','Daha sonra bu ülkeye geri dönüş'),body:T('هدف سفر جدید، اعتبار مجوز قبلی و نیاز به درخواست تازه را از مرجع رسمی بررسی کن. اگر اقامت قبلی تمام یا لغو شده باشد، روی آن برای ورود دوباره حساب نکن. سابقهٔ تحصیل به‌تنهایی اجازهٔ ورود یا اقامت بعدی ایجاد نمی‌کند.','Check your new travel purpose, validity of any previous permit and whether a new application is required. Do not rely on an expired or cancelled permit for re-entry. Previous study alone does not confer future entry or residence rights.','Yeni seyahat amacı, önceki iznin geçerliliği ve yeni başvuru gerekliliğini resmî makamdan doğrulayın. Süresi dolmuş veya iptal edilmiş izne dayanmayın. Önceki eğitim tek başına yeni giriş veya ikamet hakkı sağlamaz.')},
];
