import {z} from 'zod';
export const ratingKeys=['education','professors','campus','facilities','administration','internationalSupport','studentLife','location','costValue','accommodation','career'] as const;
export const reviewSchema=z.object({program:z.string().min(1).max(300),degree:z.string().min(1).max(80),nationality:z.string().min(1).max(100),yearStarted:z.number().int().min(1950).max(2100),studentType:z.enum(['student','graduate']),overall:z.number().min(1).max(10),ratings:z.object(Object.fromEntries(ratingKeys.map(k=>[k,z.number().min(1).max(10)])) as Record<typeof ratingKeys[number],z.ZodNumber>),likes:z.string().min(10).max(3000),improvements:z.string().min(10).max(3000),advice:z.string().min(10).max(3000),monthlyCost:z.number().min(0).max(100000).nullable(),currency:z.enum(['USD','EUR','TRY']),accommodationType:z.string().max(100),chooseAgain:z.boolean().nullable(),photos:z.array(z.string().regex(/^\/api\/university-media\/[a-f0-9-]+$/)).max(5),evidence:z.array(z.string().regex(/^[a-f0-9-]+$/)).max(3),consent:z.literal(true)});
export type StudentReview=z.infer<typeof reviewSchema>;
export const storySchema=z.object({displayName:z.string().min(1).max(60),program:z.string().max(300),origin:z.string().max(100),year:z.string().max(50),why:z.string().min(10).max(3000),firstMonth:z.string().min(10).max(3000),expenses:z.string().max(1500),surprise:z.string().max(1500),challenge:z.string().max(1500),wish:z.string().max(1500),photos:z.array(z.string().regex(/^\/api\/university-media\/[a-f0-9-]+$/)).max(5),video:z.string().max(2000).refine(s=>s===''||/^https:\/\//.test(s)),consent:z.literal(true)});
export const stageKeys=['selected','eligibility','application','admission','visa','accommodation','flight','transfer','registration','studentLife'] as const;
export const statuses=['not_started','in_progress','waiting_student','waiting_university','completed'] as const;
export const stageSchema=z.object({key:z.enum(stageKeys),status:z.enum(statuses),action:z.string().max(1000),documents:z.array(z.string().max(300)).max(20),date:z.string().max(30),advisor:z.string().max(150)});
export const journeySchema=z.object({uploads:z.array(z.object({id:z.string().uuid(),name:z.string().max(150)})).max(20).default([]),stages:z.array(stageSchema).length(10),notes:z.string().max(3000),semesterStart:z.string().max(30),accommodation:z.string().max(500),flight:z.string().max(500),transfer:z.string().max(500)}).refine(v=>new Set(v.stages.map(s=>s.key)).size===10,'All stages must be unique');
export function initialJourney(){return {uploads:[],stages:stageKeys.map(key=>({key,status:key==='selected'?'completed':'not_started',action:'',documents:[],date:'',advisor:''})),notes:'',semesterStart:'',accommodation:'',flight:'',transfer:''};}
export function satisfaction(reviews:StudentReview[]){const count=reviews.length;if(count<5)return {count,available:false};const avg=(get:(r:StudentReview)=>number)=>Math.round(reviews.reduce((s,r)=>s+get(r),0)/count*10)/10;const again=reviews.filter(r=>r.chooseAgain!==null);const groups:Record<string,StudentReview[]>={};for(const r of reviews)(groups[r.nationality.toLocaleLowerCase()]||=[]).push(r);return {count,available:true,overall:avg(r=>r.overall),ratings:Object.fromEntries(ratingKeys.map(k=>[k,avg(r=>r.ratings[k])])),chooseAgain:again.length>=5?Math.round(again.filter(r=>r.chooseAgain).length/again.length*100):null,chooseAgainCount:again.length,insights:Object.entries(groups).filter(([,g])=>g.length>=10).map(([nationality,g])=>({nationality,count:g.length,overall:Math.round(g.reduce((s,r)=>s+r.overall,0)/g.length*10)/10})),costs:['USD','EUR','TRY'].map(currency=>{const g=reviews.filter(r=>r.monthlyCost!==null&&r.currency===currency);return g.length>=10?{currency,count:g.length,average:Math.round(g.reduce((s,r)=>s+r.monthlyCost!,0)/g.length)}:null}).filter(Boolean)};}
