import {universities} from '@/app/university-price-data';
import {universityVisuals} from '@/app/university-visuals';
import records from '@/app/university-price-records.json';
import {T} from '@/app/international-data';
import {newUniversity,type University,type CampusMedia} from './university-model';
const slugs:Record<string,string>={atlas:'istanbul-atlas-university',medipol:'medipol-university',kent:'istanbul-kent-university',fenerbahce:'fenerbahce-university',beykoz:'beykoz-university',topkapi:'istanbul-topkapi-university'};
const discountLabels:Record<string,ReturnType<typeof T>>={regional:T('شهریهٔ منطقه‌ای','Regional fee','Bölgesel ücret'),cash:T('پرداخت نقدی','Advance payment','Peşin ödeme'),scholarship25:T('بورس ۲۵٪ — عنوان فایل','25% scholarship — source heading','%25 burs — kaynak başlığı'),scholarship15:T('بورس ۱۵٪ — عنوان فایل','15% scholarship — source heading','%15 burs — kaynak başlığı'),cash10:T('نقدی ۱۰٪ — عنوان فایل','10% advance — source heading','%10 peşin — kaynak başlığı'),cash25:T('نقدی ۲۵٪ — عنوان فایل','25% cash — source heading','%25 peşin — kaynak başlığı'),cash15:T('نقدی ۱۵٪ — عنوان فایل','15% cash — source heading','%15 peşin — kaynak başlığı')};
const tours:Record<string,{label:string,url:string}[]>={atlas:[{label:'Vadi',url:'https://www.atlas.edu.tr/sanaltur/'}],medipol:[{label:'Medipol',url:'https://sanaltur.medipol.edu.tr/'}],kent:[{label:'Kağıthane',url:'https://www.kent.edu.tr/sanal-tur/kagithane/'},{label:'Taksim',url:'https://www.kent.edu.tr/sanal-tur/taksim/'}]};
function price(v:unknown){return typeof v==='number'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(v):v==null?'':String(v);}
function degree(r:typeof records[number]){const s=`${r.program} ${r.faculty}`.toLocaleLowerCase('tr');return /doktora|doctoral|phd/.test(s)?'phd':/yüksek lisans|master|lisansüstü/.test(s)?'master':/meslek yüksekokul|ön lisans|associate/.test(s)?'associate':/hazırlık/.test(s)?'other':/fakülte|bachelor|lisans/.test(s)?'bachelor':'other';}
export const universitySeeds:University[]=universities.map(u=>{const visual=universityVisuals[u.slug as keyof typeof universityVisuals];const base=newUniversity();const source=u.slug==='medipol'?'/prices/medipol-25-15-2026-2027.xlsx':`/prices/${u.slug}-2026-2027.pdf`;
const campus:CampusMedia={id:'campus',label:T('پردیس دانشگاه','University campus','Üniversite kampüsü'),category:'campus',type:'image',url:visual.image,thumbnail:visual.image,source:visual.source};
return {...base,id:u.slug,slug:slugs[u.slug],legacySlug:u.slug,published:true,name:u.name,officialName:u.name.tr,heroImage:visual.image,city:T('استانبول','Istanbul','İstanbul'),description:T('پردیس، رشته‌ها و لیست شهریهٔ این دانشگاه در استانبول را بشناسید و مسیر درخواست پذیرش خود را با Creator Group آغاز کنید.','Discover this Istanbul university’s campus, programmes and supplied tuition schedules, then plan your application with Creator Group.','İstanbul’daki bu üniversitenin kampüsünü, programlarını ve gönderilen ücret listelerini keşfedin; başvurunuzu Creator Group ile planlayın.'),languages:[...new Set(records.filter(r=>r.university===u.slug).map(r=>/ingilizce|english/.test(r.program.toLocaleLowerCase('tr'))?'English':/türkçe|turkish/.test(r.program.toLocaleLowerCase('tr'))?'Türkçe':'').filter(Boolean))],officialWebsite:visual.website,feeNotice:u.note,campusMedia:[campus,...(u.slug==='kent'?[{...campus,id:'taksim',label:T('پردیس تکسیم','Taksim campus','Taksim kampüsü'),url:'/images/universities/kent-taksim.webp',thumbnail:'/images/universities/kent-taksim.webp',source:'https://www.kent.edu.tr/kampusler-0017079'}]:u.slug==='beykoz'?[{...campus,id:'social',label:T('پردیس علوم اجتماعی','Social sciences campus','Sosyal bilimler kampüsü'),url:'/images/universities/beykoz-social.webp',thumbnail:'/images/universities/beykoz-social.webp'},{...campus,id:'business',label:T('پردیس کسب‌وکار و مدیریت','Business & management campus','İşletme ve yönetim kampüsü'),url:'/images/universities/beykoz-business.webp',thumbnail:'/images/universities/beykoz-business.webp'}]:[])],campus360:(tours[u.slug]||[]).map((t,i)=>({id:`tour-${i}`,label:T(t.label,t.label,t.label),category:'campus',type:'tour',url:t.url,thumbnail:u.slug==='kent'&&i===1?'/images/universities/kent-taksim.webp':visual.image,source:t.url})),virtualTour:tours[u.slug]?.[0]?.url||'',feeSources:u.slug==='medipol'?[{label:'2026–2027 / 25-15',url:source},{label:'2026–2027 / Kopya',url:'/prices/medipol-copy-2026-2027.xlsx'}]:[{label:'2026–2027 / PDF',url:source}],programs:records.filter(r=>r.university===u.slug).map((r,i)=>({id:`${u.slug}-${i}`,name:r.program,degree:degree(r),language:/ingilizce|english/.test(r.program.toLocaleLowerCase('tr'))?'English':/türkçe|turkish/.test(r.program.toLocaleLowerCase('tr'))?'Türkçe':'',duration:r.duration,basis:r.basis as 'annual'|'program'|'source',originalTuition:price(r.values.base),discounts:Object.entries(r.values).filter(([k,v])=>discountLabels[k]&&v!=null).map(([k,v])=>({label:discountLabels[k],value:price(v)})),creatorPrice:'',source:u.slug==='medipol'?`/prices/medipol-${r.sourceVersion==='copy'?'copy':'25-15'}-2026-2027.xlsx`:source,sourceReference:`${u.slug==='medipol'?'Row':'Page'} ${r.sourcePage}`,sourceVersion:r.sourceVersion})),updatedAt:'2026-10-03T00:00:00Z'};});
