import {z} from 'zod';
export const languages=['fa','en','tr'] as const;
const text=z.object({fa:z.string().max(8000),en:z.string().max(8000),tr:z.string().max(8000)});
const url=z.string().max(2000).refine(s=>s===''||/^https:\/\//.test(s)||/^\/(images|api\/university-media|brand|prices)\/[a-zA-Z0-9/_.,%-]+$/.test(s),'Use HTTPS or a uploaded image');
export const degreeSchema=z.enum(['bachelor','master','phd','associate','other']);
export const programSchema=z.object({id:z.string().max(120),name:z.string().min(1).max(300),degree:degreeSchema,language:z.string().max(100),duration:z.string().max(100),basis:z.enum(['annual','program','source']),originalTuition:z.string().max(120),discounts:z.array(z.object({label:text,value:z.string().max(120)})).max(15),creatorPrice:z.string().max(120),source:url,sourceReference:z.string().max(150),sourceVersion:z.string().max(80)});
export const mediaSchema=z.object({id:z.string().max(120),label:text,category:z.enum(['campus','entrance','classrooms','laboratories','library','cafeteria','studentLife','sports','dormitory']),type:z.enum(['image','panorama','tour','video']),url:url,thumbnail:url,source:url});
const requirement=z.object({title:text,body:text,source:url});
export const universitySchema=z.object({id:z.string().min(1).max(120),slug:z.string().min(2).max(100).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),legacySlug:z.string().max(100),published:z.boolean(),name:text,officialName:z.string().max(300),country:text,countryCode:z.string().regex(/^[A-Z]{2}$/),city:text,logo:url,heroImage:url,heroVideo:url,description:text,universityType:text,languages:z.array(z.string().max(100)).max(20),ranking:text,yearFounded:z.number().int().min(1000).max(2100).nullable(),location:text,coordinates:z.object({lat:z.number().min(-90).max(90),lng:z.number().min(-180).max(180)}).nullable(),tuitionRange:text,programs:z.array(programSchema).max(1000),scholarships:z.array(requirement).max(50),admissionRequirements:z.array(requirement).max(50),faq:z.array(requirement).max(30).default([]),applicationDeadlines:z.array(requirement).max(30),processingTime:text,campusMedia:z.array(mediaSchema).max(100),campus360:z.array(mediaSchema).max(100),virtualTour:url,universityVideo:url,dormitory:text,studentLife:text,nearbyPlaces:z.array(z.object({type:z.string().max(100),name:text,description:text,url})).max(50),livingCosts:text,gallery:z.array(mediaSchema).max(100),officialWebsite:url,feeNotice:text,feeSources:z.array(z.object({label:z.string().max(200),url})).max(20),eligibilityRules:z.array(z.object({degree:degreeSchema,programId:z.string().max(120),nationalities:z.array(z.string().max(100)).max(300),educations:z.array(z.string().max(100)).max(10),languages:z.array(z.string().max(100)).max(20),result:z.enum(['review','eligible','ineligible']),explanation:text,source:url,validUntil:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)})).max(100),updatedAt:z.string().max(50)});
export type University=z.infer<typeof universitySchema>;
export type CampusMedia=z.infer<typeof mediaSchema>;
export type Program=z.infer<typeof programSchema>;
export const blankText={fa:'',en:'',tr:''};
export function newUniversity():University{return {id:crypto.randomUUID(),slug:'new-university',legacySlug:'',published:false,name:{...blankText},officialName:'',country:{fa:'ترکیه',en:'Türkiye',tr:'Türkiye'},countryCode:'TR',city:{...blankText},logo:'',heroImage:'',heroVideo:'',description:{...blankText},universityType:{...blankText},languages:[],ranking:{...blankText},yearFounded:null,location:{...blankText},coordinates:null,tuitionRange:{...blankText},programs:[],scholarships:[],admissionRequirements:[],faq:[],applicationDeadlines:[],processingTime:{...blankText},campusMedia:[],campus360:[],virtualTour:'',universityVideo:'',dormitory:{...blankText},studentLife:{...blankText},nearbyPlaces:[],livingCosts:{...blankText},gallery:[],officialWebsite:'',feeNotice:{...blankText},feeSources:[],eligibilityRules:[],updatedAt:new Date().toISOString()};}
