import {z} from 'zod';
import {getRawDb} from '@/db/raw';
import {isAdmin,sameOrigin,readJSON,audit} from '@/lib/platform-security';
import {listUniversities,saveUniversity} from '@/lib/university-store';
import {universitySchema} from '@/lib/university-model';
import {destinationContent} from '@/lib/destination-model';
import {journeySchema} from '@/lib/student-model';
import {rows} from '@/lib/platform-store';
export const dynamic='force-dynamic';
export async function GET(r:Request){try{if(!await isAdmin(r))return Response.json({error:'Please sign in'},{status:401});const reviews=await rows("SELECT json_object('id',r.id,'universityId',r.university_id,'studentId',r.student_id,'status',r.status,'content',json(r.content),'evidence',json(r.evidence),'name',a.name,'email',a.email) AS item FROM student_reviews r JOIN student_accounts a ON a.id=r.student_id ORDER BY r.updated_at DESC LIMIT 100");const stories=await rows("SELECT json_object('id',id,'universityId',university_id,'status',status,'content',json(content)) AS item FROM student_stories ORDER BY updated_at DESC LIMIT 100");const journeys=await rows("SELECT json_object('id',j.id,'studentId',j.student_id,'name',a.name,'email',a.email,'universityId',j.university_id,'programId',j.program_id,'content',json(j.content)) AS item FROM student_journeys j JOIN student_accounts a ON a.id=j.student_id ORDER BY j.updated_at DESC LIMIT 100");const content=await rows("SELECT json_object('id',id,'kind',kind,'universityId',university_id,'published',published,'content',json(content)) AS item FROM platform_content WHERE kind<>'media' ORDER BY updated_at DESC LIMIT 200");const trips=await rows("SELECT json_object('id',t.id,'name',a.name,'email',a.email,'universityId',t.university_id,'kind',t.kind,'status',t.status,'content',json(t.content)) AS item FROM travel_requests t JOIN student_accounts a ON a.id=t.student_id ORDER BY t.created_at DESC LIMIT 100");const questions=await rows("SELECT json_object('id',id,'question',question,'answer',answer,'universityId',university_id,'ambassadorId',ambassador_id,'status',status) AS item FROM ambassador_questions ORDER BY created_at DESC LIMIT 100");const reports=await rows("SELECT json_object('id',id,'kind',kind,'itemId',item_id,'reason',reason) AS item FROM platform_reports ORDER BY created_at DESC LIMIT 100");const log=await rows("SELECT json_object('action',action,'entityId',entity_id,'details',json(details),'createdAt',created_at) AS item FROM admin_audit ORDER BY created_at DESC LIMIT 100");return Response.json({universities:await listUniversities(true),reviews,stories,journeys,content,trips,questions,reports,log},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Admin unavailable'},{status:503});}}
export async function POST(r:Request){if(!sameOrigin(r))return Response.json({error:'Invalid origin'},{status:403});try{if(!await isAdmin(r))return Response.json({error:'Please sign in'},{status:401});const p=await readJSON(r),db=getRawDb();if(p.action==='university'){const u=universitySchema.parse(p.university);if(u.published&&(!u.name.en||!u.name.fa||!u.name.tr||!u.heroImage||!u.officialWebsite))return Response.json({error:'Publishing requires name in all languages, campus hero image and official website'},{status:400});const old=(await listUniversities(true)).find(x=>x.id===u.id);if(old&&old.slug!==u.slug)return Response.json({error:'Keep the existing slug to preserve student links'},{status:400});u.updatedAt=new Date().toISOString();await saveUniversity(u);await audit('university.save',u.id,{published:u.published});return Response.json({ok:true});}
if(p.action==='review'){const v=z.object({id:z.string().uuid(),status:z.enum(['unverified','verification_pending','verified_student','verified_graduate','rejected']),method:z.enum(['manual','student-document','university-email','application-record','none']),confirmed:z.boolean()}).parse(p);if(v.status.startsWith('verified')&&(!v.confirmed||v.method==='none'))return Response.json({error:'Evidence verification must be confirmed before publication'},{status:400});const record=await db.prepare('SELECT content FROM student_reviews WHERE id=?').bind(v.id).first<{content:string}>();if(!record)return Response.json({error:'Review not found'},{status:404});const source=JSON.parse(record.content);if(v.status==='verified_graduate'&&source.studentType!=='graduate'||v.status==='verified_student'&&source.studentType!=='student')return Response.json({error:'Verification status must match reviewer type'},{status:400});await db.prepare('UPDATE student_reviews SET status=?,verification_method=?,updated_at=? WHERE id=?').bind(v.status,v.method,Date.now(),v.id).run();await audit('review.moderate',v.id,{status:v.status,method:v.method});return Response.json({ok:true});}
if(p.action==='story'){const v=z.object({id:z.string().uuid(),status:z.enum(['pending','published','rejected'])}).parse(p);if(v.status==='published'){const verified=await db.prepare("SELECT s.id FROM student_stories s WHERE s.id=? AND EXISTS(SELECT 1 FROM student_reviews r WHERE r.student_id=s.student_id AND r.university_id=s.university_id AND r.status IN ('verified_student','verified_graduate'))").bind(v.id).first();if(!verified)return Response.json({error:'A verified student is required before publishing their story'},{status:400});}await db.prepare('UPDATE student_stories SET status=?,updated_at=? WHERE id=?').bind(v.status,Date.now(),v.id).run();await audit('story.moderate',v.id,{status:v.status});return Response.json({ok:true});}
if(p.action==='journey'){const v=z.object({id:z.string().uuid(),content:journeySchema}).parse(p);await db.prepare('UPDATE student_journeys SET content=?,updated_at=? WHERE id=?').bind(JSON.stringify(v.content),Date.now(),v.id).run();await audit('journey.update',v.id);return Response.json({ok:true});}
if(p.action==='content'){const v=destinationContent.parse(p.record);if(v.content.lastVerifiedAt>new Date().toISOString().slice(0,10))return Response.json({error:'Verification date cannot be in the future'},{status:400});await db.prepare('INSERT INTO platform_content(id,kind,university_id,content,published,updated_at) VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,university_id=excluded.university_id,content=excluded.content,published=excluded.published,updated_at=excluded.updated_at').bind(v.id,v.kind,v.universityId,JSON.stringify(v.content),v.published?1:0,Date.now()).run();await audit('content.save',v.id,{kind:v.kind,published:v.published});return Response.json({ok:true});}
if(p.action==='trip'){const v=z.object({id:z.string().uuid(),status:z.enum(['requested','in_progress','awaiting_student','confirmed','cancelled']),reference:z.string().max(500)}).parse(p);if(v.status==='confirmed'&&!v.reference)return Response.json({error:'Confirmation needs a real provider reference'},{status:400});await db.prepare("UPDATE travel_requests SET status=?,content=json_set(content,'$.confirmationReference',?) WHERE id=?").bind(v.status,v.reference,v.id).run();await audit('travel.update',v.id,{status:v.status});return Response.json({ok:true});}
if(p.action==='question'){const v=z.object({id:z.string().uuid(),status:z.enum(['approved','answered','rejected'])}).parse(p);await db.prepare('UPDATE ambassador_questions SET status=? WHERE id=?').bind(v.status,v.id).run();await audit('ambassador.moderate',v.id,{status:v.status});return Response.json({ok:true});}
if(p.action==='block-ambassador'){const v=z.object({studentId:z.string().uuid(),universityId:z.string().max(120),blocked:z.boolean()}).parse(p);await db.prepare('UPDATE student_ambassadors SET blocked=? WHERE student_id=? AND university_id=?').bind(v.blocked?1:0,v.studentId,v.universityId).run();await audit('ambassador.block',v.studentId,{blocked:v.blocked});return Response.json({ok:true});}
return Response.json({error:'Unknown action'},{status:400});}catch(e){if(e instanceof z.ZodError)return Response.json({error:e.issues.slice(0,3).map(x=>`${x.path.join('.')}: ${x.message}`).join('; ')},{status:400});console.error('Admin write unavailable');return Response.json({error:'Save failed; please retry'},{status:503});}}
